### ISSUE TITLE
Channel based key generation

### ISSUE THREAD

**Issue by hullspokes** [NVlabs/sionna#108]
Hello Sionna Team,

thank you very much for the great tool. It is overwhelmingly good and also great documented. 
I am a computer science student with little or only some basic knowledge in wireless communications.

I have already played around a bit with the simulator and was able to understand most of the tutorial.

Since I am very interested in physical layer security, I would like to simulate and try Secret Key Extraction between Alice and Bob in the simulator. 
For this I would like to use the channel estimation to perform a quantization, so that in the end Alice and Bob have the same key based on the exchanged pilot signals and the subsequent channel estimation. 

Unfortunately, I'm just a bit lost and am overwhelmed by the large number of functions in Sionna.
I would like to have the Channel Estimates in each case once from the perspective of Alice and once from the perspective of Bob. What is the best way to do this? Is this even currently feasible in Sionna?

Many thanks in advance.

**Comment by jhoydis** [comment]
Hi,

So, you assume some kind of TDD system where first A transmits to B and then B to A while the channel stays constant during these transmissions?

Do you assume OFDM or a simple frequency flat channel?

**Comment by jhoydis** [comment]
There are many different ways in which you can achieve that, depending on your system model. 

If you just want two noisy observations of a flat-fading channel coefficient (which would be equivalent to TDD with perfect reciprocity and LS channel estimation), you can simply do this: 
```
import sionna
from sionna.channel import AWGN, GenerateFlatFadingChannel
gen_h = GenerateFlatFadingChannel(1,1) # single transmit and receive antenna
awgn = AWGN()

batch_size = 1 # Number of channel realizations
no = 0.01      # Noise variance = equal to MSE of the channel estimate

h = tf.squeeze(gen_h(batch_size))
h_a = awgn([h, 0.01])   # Channel for Alice
h_b = awgn([h, 0.01])   # Channel for Bob
```

**Comment by hullspokes** [comment]
Ok, thank you, I get the idea now.
I think by now the solved in my head is broken and I can then assemble more complicated system models myself.

Thank you for the quick and very helpful answer.
