### ISSUE TITLE
Creating Custom Scenes

### ISSUE THREAD

**Issue by ishaanmht** [NVlabs/sionna#114]
Hello,

I am a newbie to Sionna.

I have gone through tutorials for Ray tracing. However, it is not clear how to load custom scenes in the software. Particularly, I want to simulate wifi measurements in an indoor setting. I have a CAD model for an indoor environment. I am not sure how should I setup XML files to use this indoor scene in sionna.

Regards,
Ishaan

**Comment by akdd11** [comment]
Hello Ishaan,

the scenes have to be in a Mitsuba file format (xml). Can you import your CAD model in Blender?
If so, you can export it from Blender with the Mitsuba add-on.

- Assign the correct materials (see the Youtube video tutorial for raytracing)
- Install the `mitsuba `package in the Blender python environment.
- Install the `mitsuba-blender` add-on.
- `File > Export > Mitsuba`, check correct orientation and also select `Export IDs`
