### ISSUE TITLE
Problem with polarization direction

### ISSUE THREAD

**Issue by zhengxf99** [NVlabs/sionna#115]
Hi Sionna team,

If my understanding is correct, there is a bug with polarization direction calculation in current version.

In line 452 of antenna.py,
`slant_angle = 0 if polarization == "VH" else -PI/4`
which should be,
`slant_angle = 0 if polarization_type == "VH" else -PI/4`

Thanks

**Comment by jhoydis** [comment]
Good catch! This is indeed a bug. It will be corrected in the next release.
