### ISSUE TITLE
Ray Tracing Channel based key extraction

### ISSUE THREAD

**Issue by remydemy** [NVlabs/sionna#131]
Hello,

I want to build a channel-based key extraction using ray tracing. For this, I calculate the CIR based on the paths and then create an OFDM channel with the CIR. In the end, I simulate some noise on the channel with awgn.
My problem now is that h_alice and h_bob only have a shape of (48, ) which is not a lot and also not enough channel output to calculate a secure key.
Is there some way to up this shape?

In issue #108 it was proposed to use a flat fading channel and a batch_size of 1000. Is there something similar I can use for this scenario? I found the CIRDataset class, where I could set a batch_size, but I don't understand how to use the required generator in this case or if this even is the correct way.

I have added my code below.

Thank you,
Emily

```
# Load example scene
scene_munich = load_scene(sn.rt.scene.munich)

# Configure antenna array for all transmitters
scene_munich.tx_array = PlanarArray(num_rows=1,
                          num_cols=1,
                          vertical_spacing=0.5,
                          horizontal_spacing=0.5,
                          pattern="tr38901",
                          polarization="V")

# Configure antenna array for all receivers
scene_munich.rx_array = PlanarArray(num_rows=1,
                          num_cols=1,
                          vertical_spacing=0.5,
                          horizontal_spacing=0.5,
                          pattern="dipole",
                          polarization="V")

# Create transmitter
tx = Transmitter(name="tx",
              position=[8.5,21,27],
              orientation=[0,0,0])
scene_munich.add(tx)

# Create a receiver
rx = Receiver(name="rx",
           position=[45,90,1.5],
           orientation=[0,0,0])
scene_munich.add(rx)

# TX points towards RX
tx.look_at(rx)

scene_munich.frequency = 2.14e9
scene_munich.synthetic_array = True

paths_munich = scene_munich.compute_paths()

# Default parameters in the PUSCHConfig
subcarrier_spacing = 15e3
fft_size = 48

# Transform paths into channel impulse responses
p2c = Paths2CIR(sampling_frequency=subcarrier_spacing,
                num_time_steps=1,
                scene=scene_munich)
a, tau = p2c(paths_munich.as_tuple())

# Compute frequencies of subcarriers and center around carrier frequency
frequencies = subcarrier_frequencies(fft_size, subcarrier_spacing)

# Compute the frequency response of the channel at frequencies.
h_freq = tf.squeeze(cir_to_ofdm_channel(frequencies,
                             a,
                             tau,
                             normalize=True)) # Non-normalized includes path-loss

# Setup resource grid
rg = ResourceGrid(num_ofdm_symbols=1,
                  fft_size=fft_size,
                  subcarrier_spacing=15e3)

# Generate time channel from CIR
l_min, l_max = time_lag_discrete_time_channel(rg.bandwidth)
h_time = cir_to_time_channel(rg.bandwidth, a, tau, l_min=l_min, l_max=l_max, normalize=True)

# Generate OFDM channel from time channel
h_freq_hat = tf.squeeze(time_to_ofdm_channel(h_time, rg, l_min))

awgn = AWGN() # -> Used to simulate internal noise of wireless receivers

no = 0.01 # MSE of the channel estimate (Noise variance)

h_alice = awgn([h_freq_hat, no])
h_bob = awgn([h_freq_hat, no])

```

**Comment by SebastianCa** [comment]
Hi,

there are two different ways how you can get longer/multiple keys and the solution depends on your application:
- Simulate more subcarriers: in your case you need to increase the parameter `fft_size`. This however just computes a larger Fourier transform from the same sampled channel responses.
- Sample from multiple positions: you can simply add multiple receivers at random positions (see [code example](https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Introduction.html#Site-specifc-Link-Level-Simulations)).
This would lead to the sampling of more channel realizations that could be independent from each other if the positions are sufficiently spaced.

A quick remark regarding the code example above (without knowing your exact setup): at the moment Alice and Bob sample `h_freq`from the same position (from receiver `rx`) but with a different noise realization. My guess is that in practice they are at different positions, i.e., `h_freq` is already different for Alice and Bob.

And another remark: it is not clear to me why you need to sample `h_freq_hat` from the time domain channel. Wouldn't it be sufficient to directly use `h_freq`?

**Comment by remydemy** [comment]
Ah yes, I thought about setting ``fft_size`` to a higher value already but I was unsure if that would be accurate. Because as far as I understood the docs the `fft_size` resembles the number of subcarriers, but would for example 1000 subcarriers in a channel be an adequate representation of the real world or would it be ok to use such a high number, because it's just a simulation.

Thanks for all the remarks on my code btw!

(I'm a computer science major and have yet to find out a lot about signal processing😂)

**Comment by SebastianCa** [comment]
In practice, >1000 subcarriers are not unusual. However, please keep in mind that the entropy of your key will be most likely limited by diversity of the channel / complexity of the underlying scenario.
In other words: the additional sub-carriers become predictable.
