### ISSUE TITLE
Channel decoder should (optionally) return CRC status

### ISSUE THREAD

**Issue by catkira** [NVlabs/sionna#134]
As discussed in [this ](https://github.com/NVlabs/sionna/pull/84) PR, it would be nice if the decoder functions return the CRC status (ok or failed). Sebastian suggested to add an extra flag `return_crc_status` to the decoder routine to enable the CRC status output optionally. Should I make a PR for this or is somebody else already on it?

**Comment by SebastianCa** [comment]
We plan to integrate this feature in the next release of Sionna. There is no need for an additional PR.
