### ISSUE TITLE
Comments Error in 'tdl.py'

### ISSUE THREAD

**Issue by WhatIsSurprise** [NVlabs/sionna#136]
I found in `tdl.py`, line 148-151
```python
'''
    delay_spread : float
        RMS delay spread [s].
        For the "A30", "B100", and "C300" models, the delay spread must be set
        to 10ns, 100ns, and 300ns, respectively.
'''
```

the delay spread of TDL A30 should be 30ns, not 10ns.

**Comment by faycalaa** [comment]
Hi,

Thank you for reporting this typo. It will be fixed in the next release.

Note that this is only a typo in the documentation. The code should work as expected.
