### ISSUE TITLE
Material 'itu_marble' is used but not well defined

### ISSUE THREAD

**Issue by remydemy** [NVlabs/sionna#140]
Hello,

I have a scene with one transmitter and one receiver. When I try to compute the paths between them with `compute_paths()` from a specific frequency onwards I get the following ValueError: `Material 'itu_marble' is used by the object  'Arc_de_Triomphe-itu_marble' but is not well-defined`. 
I get the same error for scene.etoile as well as scene.munich, only that for the munich scene it changes to `Material 'itu_marble' is used by the object  'Heilig_Geist-itu_marble' but is not well-defined.`
For munich this happens when I set the frequency to `> 40e9` Hz and for paris when I set the frequency to `> 60e9` Hz.

Is there something I have to specifically set for such high frequencies?

Best regards,
Emily

**Comment by faycalaa** [comment]
Hi Emily,

The ITU materials are only well-defined within certain frequency ranges, specific to each material.
The valid frequency ranges are indicated the documentation:
https://nvlabs.github.io/sionna/api/rt.html#radio-materials

**Comment by remydemy** [comment]
Ahh did not know that. 
Thank you!
