### ISSUE TITLE
SIONNA installation issue

### ISSUE THREAD

**Issue by RahulSinghGulia** [NVlabs/sionna#15]
Hi team,

First of all, I would like to thank you for developing this product. It's really intriguing to read the documentation posted on the official website. And I would also like to install and learn more about it. 

I have a few queries regarding the installation process since I am new to the Conda environment. 
1. Should we run these commands after I activate my "Conda Environment".
2. If the above is not true, I have installed the SIONNA package in a Conda environment and received the following error.

(CondaRahul) rahul@rahul-VirtualBox:~/Documents/NVlabs-sionna$ python
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> **import sionna**
2022-05-05 05:29:21.261805: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-05 05:29:21.261840: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

>>> **print(sionna._version_)**
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'sionna' has no attribute '_version_'. Did you mean: '__version__'?

It would be a great help if anyone can suggest me a solution to my queries. Looking forward to hearing back from you.

Thank you,
Rahul Singh Gulia

**Comment by SebastianCa** [comment]
You should use `print(sionna.__version__)` to print the version of Sionna you have installed. See the [installation page](https://nvlabs.github.io/sionna/installation.html) for details.

Note that the above warnings are related to Tensorflow and your local CUDA installation and can be ignored if you don't have GPUs.
