### ISSUE TITLE
The sionna.rt.Receiver.look_at() doesn't actually lock on a desired direction. 

### ISSUE THREAD

**Issue by AbdolvakilFazli** [NVlabs/sionna#155]
I'm trying to do sensing using Sionna. 
but the look_at()  function seems not to work,
With forcing the tx(rx).look_at(object_location), even though the orientation of tx(rx) changes but there is no reflection path from object_locatoin. (I have tried many alternatives including changing the object type, material, locations, "stochastic" vs "exhaustive" method etc, but still didn't work)
Would you clarify why this happening? and how I can actually steer the beam so that it just lock on a certain direction?

**Comment by jhoydis** [comment]
Hi, I could imagine that the reason for this behaviour is that there is no specular (reflected) path  TX->object->RX. The orientation of the TX and RX would only impact the strength of the path (if there is any).

For sensing applications, such as radar, you are typically looking for diffuse reflections, i.e., scattering, which Sionna RT does not yet implement.

**Comment by AbdolvakilFazli** [comment]
Thank you, does this mean that either mono-static sensing via Sionna is not possible? what about bi-static sensing?

**Comment by jhoydis** [comment]
I do not know what mono/bi-static sensing refers to. Anything requiring diffuse reflections is currently not possible.
