### ISSUE TITLE
Autoencoder.ipynb not passing bits_per_symbol to encoder

### ISSUE THREAD

**Issue by nbecker** [NVlabs/sionna#158]
In the example: Autoencoder.ipynb

In several places where encoders are constructed:
self._encoder = LDPC5GEncoder(k, n)

The encoder accepts a bits_per_symbol argument, which I assume will affect the interleaver, but this argument is not passed to the encoder constructor.  Is this an oversight?

**Comment by SebastianCa** [comment]
Hi,

Indeed, this is correct. The `num_bits_per_symbol` parameter within the `LDPC5GEncoder` only influences the interleaver's selection. Note that this feature was added in a later version of Sionna, while the Autoencoder notebook had already been included in the initial release.

The addition of the interleaver enhances the performance across all three systems. Nevertheless, the overall efficiency gains from end-to-end learning are roughly constant.

We will update the autoencoder notebook with an activated interleaver in the next release of Sionna.
