### ISSUE TITLE
Repeated radio materials in OSM-imported objects fail to render

### ISSUE THREAD

**Issue by TwiggyDaniels** [NVlabs/sionna#163]
### Overview:
When rendering/previewing scenes for ray tracing in Sionna, multiple instances of a radio materials for a single object do not appear. Ideally, Sionna would handle this issue itself, though I believe it stems from Mitsuba and can be avoided by modifying scenes in Blender.

### Example:
After importing a scene from OSM, sometimes objects can be composed of portions that you may wish to have share the same radio material:
![image](https://github.com/NVlabs/sionna/assets/22119944/35171f8f-9a48-405d-b684-a273ace8246a)

Within Blender this produces the object as shown:
![image](https://github.com/NVlabs/sionna/assets/22119944/254e8d72-302d-4aea-8c2b-343d3a3346bd)

Strangely, when previewing/rendering within Sionna this causes portions with the same material to disappear based off of their ordering within the materials list:
![image](https://github.com/NVlabs/sionna/assets/22119944/14cd578d-3c07-412f-a64f-a1e87982dc10)

This is probably an issue with Mitsuba handling the rendering. I am sure someone else will run into this issue and I wanted to tag something.

### Workarounds:
There are two Blender workarounds that I expect will work that I am about to try in the meantime:

1.  Combining the portions of the object into a single mesh and tagging them as a single radio material.

2. Tagging the second portion as a new material with the same properties and manually adding it to the radio materials list within Sionna, i.e. labeling it `itu_brick.001` within Blender and using `sionna.rt.RadioMaterial` within Sionna.

**Comment by merlinND** [comment]
Hello @TwiggyDaniels,

Thank you for your detailed report! I've submitted a proposed fix for the mitsuba-blender addon: https://github.com/NVlabs/sionna/issues/163.
I'll leave this issue open until it is merged.

**Comment by merlinND** [comment]
The PR has been merged, could you please check if the problem is resolved by the latest commit?
https://github.com/mitsuba-renderer/mitsuba-blender/commit/3336eeca316fe617689bd1020c53a442acd5221c

**Comment by TwiggyDaniels** [comment]
Confirming that it seems to be fixed for my case.
