### ISSUE TITLE
LDPC5GDecoder failure

### ISSUE THREAD

**Issue by aaronwom** [NVlabs/sionna#164]
I have been looking at the Tutorial "5G Channel Coding and Rate Matching" to learn how to use the Sionna LDPC Decoder. I have tested several of the decoders in the tutorial, and I was able to successfully encode and decode a string of bits with most of them. However, I get the following error every time I try to use the LDPC5GDecoder:

ValueError: Exception encountered when calling layer 'system__model_13' (type System_Model).

in user code:

    File "/home/aaronw/python/lb_decode/sionna_tutorial.py", line 162, in call  *
        u_hat = self.decoder(llr_ch) # run FEC decoder (incl. rate-recovery)
    File "/opt/anaconda3/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "/tmp/__autograph_generated_filecyh_or1v.py", line 98, in tf__call
        ag__.if_stmt(ag__.not_(ag__.ld(self)._stateful), if_body_2, else_body_2, get_state_2, set_state_2, ('msg_vn', 'x_hat'), 2)
    File "/tmp/__autograph_generated_filecyh_or1v.py", line 92, in if_body_2
        x_hat = ag__.converted_call(ag__.converted_call(ag__.ld(super), (), None, fscope).call, (ag__.ld(llr_5g),), None, fscope)
    File "/tmp/__autograph_generated_file8abc71tl.py", line 173, in tf__call
        (_, msg_vn, _) = ag__.converted_call(ag__.ld(tf).while_loop, (ag__.ld(dec_stop), ag__.ld(dec_iter), (ag__.ld(llr_ch), ag__.ld(msg_vn), ag__.ld(it))), dict(parallel_iterations=1, maximum_iterations=ag__.ld(self)._num_iter), fscope)
    File "/tmp/__autograph_generated_file8abc71tl.py", line 103, in dec_iter
        msg_vn = ag__.converted_call(ag__.ld(self)._vn_update, (ag__.ld(msg_vn), ag__.ld(llr_ch)), None, fscope_1)
    File "/tmp/__autograph_generated_fileu0e8zo2g.py", line 19, in tf___vn_update
        x = ag__.converted_call(ag__.ld(tf).add, (ag__.ld(x), ag__.ld(llr_ch)), None, fscope)

    ValueError: Exception encountered when calling layer 'ldpc5g_decoder_21' (type LDPC5GDecoder).
    
    in user code:
    
        File "/opt/anaconda3/lib/python3.10/site-packages/sionna/fec/ldpc/decoding.py", line 1376, in call  *
            x_hat = super().call(llr_5g)
        File "/opt/anaconda3/lib/python3.10/site-packages/sionna/fec/ldpc/decoding.py", line 955, in dec_iter  *
            msg_vn = self._vn_update(msg_vn, llr_ch)
        File "/opt/anaconda3/lib/python3.10/site-packages/sionna/fec/ldpc/decoding.py", line 518, in _vn_update  *
            x = tf.add(x, llr_ch)
    
        ValueError: Dimensions must be equal, but are 625 and 196 for '{{node ldpc5g_decoder_21/while/Add_1}} = AddV2[T=DT_FLOAT](ldpc5g_decoder_21/while/RaggedReduceSum/UnsortedSegmentSum, ldpc5g_decoder_21/while/Placeholder)' with input shapes: [625,?], [196,?].
    
    
    Call arguments received by layer 'ldpc5g_decoder_21' (type LDPC5GDecoder):
      • inputs=tf.Tensor(shape=(None, 128), dtype=float32)

Call arguments received by layer 'system__model_13' (type System_Model):
  • batch_size=tf.Tensor(shape=(), dtype=int32)
  • ebno_db=tf.Tensor(shape=(), dtype=float32)

I do not have a GPU that is capable of processing, and I have not used tensorflow before so I am unfamiliar with the package. However, the other decoders in the tutorial work properly, so I would assume this error is not a result of the tensorflow version or my device configuration. Any advice would be greatly appreciated.

**Comment by SebastianCa** [comment]
Hi,

the TensorFlow and Sionna should also run on CPU platforms without GPU support.

Could you please provide some more details:
- Which versions of TensorFlow and Sionna you are currently using?
- Have there been any modifications to the code parameters from your end? If so, could you share those details as well and ideally an example that reproduces the error?

As a side note, remember that you can run all our notebooks directly in Google Colab [5G_Channel_Coding_Polar_vs_LDPC_Codes.ipynb](https://colab.research.google.com/github/nvlabs/sionna/blob/main/examples/5G_Channel_Coding_Polar_vs_LDPC_Codes.ipynb).

**Comment by aaronwom** [comment]
I am using python 3.9, sionna 0.14.0, and tensorflow 2.11.0. 

I have not modified any parameters. For now I have simply been copying the code from the tutorial and pasting it into a .py file that I have been running in a Spyder environment. I have tried a few other examples that I have found that use LDPC5GDecoder, and I get the same result. The error always occurs in the tf.add call of _vn_update (in sionna/fec/ldpc/decoding.py), and it is because the dimensions of the two tensor inputs are different.

Thank you for pointing me to the Google Colab. When running the code in the colab, the LDPC5GDecoder worked as I expected. Any explanation why it works on Google Colab but not locally on my computer?

**Comment by aaronwom** [comment]
I installed TF 2.12.0 and Sionna 0.14.0 using the python3 command (I am using linux environment, and previously I installed/ran everything using conda) and now it works. I am not sure why the same code/packages did not work using conda, but they worked using the linux command python3.
