### ISSUE TITLE
cannot see figure output in retmote inteprepter 

### ISSUE THREAD

**Issue by oatuy** [NVlabs/sionna#169]
Hi,

I'm using sionna in a remote python interpreter in docker via ssh. I cannot get figure output from sionna, e.g., scene.preview and scene.render, while I can get them from jupyter lab.
Is it possible to use sionna with a remote interpreter?

thanks and best regards.

**Comment by jhoydis** [comment]
Hi,

There is a method called [``scene.render_to_file()``](https://nvlabs.github.io/sionna/api/rt.html#sionna.rt.Scene.render_to_file) that you can use in such a case.

Most other functions, such as [``CoverageMap.show()``](https://nvlabs.github.io/sionna/api/rt.html#sionna.rt.CoverageMap.show), return Figure objects that you can save to file like any other figure from Matplotlib.

Hope that helps.

**Comment by oatuy** [comment]
Thanks a lot. I will use file instead.
