### ISSUE TITLE
sionna.rt.Scene. cannot be used in parallel

### ISSUE THREAD

**Issue by oatuy** [NVlabs/sionna#173]
Hi, 

I wanted to test if I can handle different scenes in parallel, but I found that once used methods such as `sionna.rt.Scene.compute_paths` in a thread or a process, error msg like the following one would come. (problem seems in mitsuba) 
Is such parallelization possible in sionna? 
 
```
 File "/root/py/rt5.py", line 51, in cm_process
    path = scene.compute_paths(max_depth=5, num_samples=20e6,
  File "/usr/local/lib/python3.8/dist-packages/sionna/rt/scene.py", line 564, in compute_paths
    paths = self._solver_paths(max_depth,
  File "/usr/local/lib/python3.8/dist-packages/sionna/rt/solver_paths.py", line 429, in __call__
    output = self._list_candidates_fibonacci(max_depth,
  File "/usr/local/lib/python3.8/dist-packages/sionna/rt/solver_paths.py", line 914, in _list_candidates_fibonacci
    source_i = mi.Int32(source_i)
  File "/usr/local/lib/python3.8/dist-packages/mitsuba/__init__.py", line 236, in __getattribute__
    raise ImportError('Before importing any packages, you must '
ImportError: Before importing any packages, you must specify the desired variant of Mitsuba using "mitsuba.set_variant(..)".
The following variants are available: scalar_rgb, scalar_spectral, cuda_ad_rgb, llvm_ad_rgb.
You can also use the MI_DEFAULT_VARIANT environment variable to define a default variant.
```

**Comment by jhoydis** [comment]
Hi,

You cannot open multiple scenes in a single notebook, but you can open multiple notebooks with different scenes in parallel. Do you have a specific use case in mind for which you would require to operate on multiple scenes in parallel?

**Comment by oatuy** [comment]
Thank you for the reply. I use the container as a remote server and access it from my local IDE, rather than using Jupyter. 
My objective is rt for a dynamic scene, so I am trying to use parallelization to accelerate the multi-frame(scene) processing to increase the “frame-rate” of rt.

**Comment by merlinND** [comment]
Hello @oatuy,

For the specific error that you encountered, you can fix it by calling `mi.set_variant()` on each thread (since the Mitsuba variant is a thread-local variable).
However, as @jhoydis mentioned, multiple scenes in the same process are not supported in Sionna.

**Comment by oatuy** [comment]
@merlinND Thank you for your suggestion. I'll definitely try. 
After some experimentation, I found that using multiple Python processes (not subprocess) was also workaround. In my case, for simple scenes, I could run over 15 processes for different scenes concurrently without experiencing noticeable increase in computing time.

**Comment by Xiaohei-Luo** [comment]
> Hello @oatuy,
> 
> For the specific error that you encountered, you can fix it by calling `mi.set_variant()` on each thread (since the Mitsuba variant is a thread-local variable). However, as @jhoydis mentioned, multiple scenes in the same process are not supported in Sionna.

Hi, Thanks for your reply. 
After trying it out, I found that multiprocessing works well, but multithreading doesn't, the program exited with an exception(Process finished with exit code -1073741819 (0xC0000005)). 

The follow is my code:

import threading
import multiprocessing
import mitsuba as mi

def load_thread(filepath):
    mi.set_variant("cuda_ad_rgb")
    mi.load_file(filepath)

def load_process(filepath):
    mi.set_variant("cuda_ad_rgb")
    mi.load_file(filepath)

if __name__ == "__main__":
    paths = "test.xml"

    # it works well.
    # process = multiprocessing.Process(target=load_process, args=(paths, ))
    # process.start()
    # process.join()

    # it exited with  exit code -1073741819 (0xC0000005).
    thread = threading.Thread(target=load_thread, args=(paths,))
    thread.start()
    thread.join()

So, i want to ask the same question, is such parallelization possible in sionna?

**Comment by Xiaohei-Luo** [comment]
> Hello @oatuy,
> 
> For the specific error that you encountered, you can fix it by calling `mi.set_variant()` on each thread (since the Mitsuba variant is a thread-local variable). However, as @jhoydis mentioned, multiple scenes in the same process are not supported in Sionna.

Hi, Thanks for your reply.
After trying it out, I found that multiprocessing works well, but multithreading doesn't, the program exited with an exception(Process finished with exit code -1073741819 (0xC0000005)).

The follow is my code:
# import threading
# import multiprocessing
# import mitsuba as mi
# 
# def load_thread(filepath):
# mi.set_variant("cuda_ad_rgb")
# mi.load_file(filepath)
# 
# def load_process(filepath):
# mi.set_variant("cuda_ad_rgb")
# mi.load_file(filepath)
# 
# if name == "main":
# paths = "test.xml"
# 
# # it works well.
##  process = multiprocessing.Process(target=load_process, args=(paths, ))
##  process.start()
##  process.join()

##  it exited with  exit code -1073741819 (0xC0000005).
# thread = threading.Thread(target=load_thread, args=(paths,))
# thread.start()
# thread.join()
So, i want to ask the same question, is such parallelization possible in sionna?

**Comment by Xiaohei-Luo** [comment]
> Hello @oatuy,
> 
> For the specific error that you encountered, you can fix it by calling `mi.set_variant()` on each thread (since the Mitsuba variant is a thread-local variable). However, as @jhoydis mentioned, multiple scenes in the same process are not supported in Sionna.

Hi, Thanks for your reply.
After trying it out, I found that multiprocessing works well, but multithreading doesn't, the program exited with an exception(Process finished with exit code -1073741819 (0xC0000005)).

The follow is my code:
`
import threading
import multiprocessing
import mitsuba as mi
def load_thread(filepath):
mi.set_variant("cuda_ad_rgb")
mi.load_file(filepath)
def load_process(filepath):
mi.set_variant("cuda_ad_rgb")
mi.load_file(filepath)
if name == "main":
paths = "test.xml"
# it works well.
process = multiprocessing.Process(target=load_process, args=(paths, ))
process.start()
process.join()
it exited with exit code -1073741819 (0xC0000005).
thread = threading.Thread(target=load_thread, args=(paths,))
thread.start()
thread.join()
`
So i wander ask the same question: Is such parallelization possible in sionna?

**Comment by Xiaohei-Luo** [comment]
> Hello @oatuy,
> 
> For the specific error that you encountered, you can fix it by calling `mi.set_variant()` on each thread (since the Mitsuba variant is a thread-local variable). However, as @jhoydis mentioned, multiple scenes in the same process are not supported in Sionna.

Hi, Thanks for your reply.
After trying it out, I found that multiprocessing works well, but multithreading doesn't, the program exited with an exception(Process finished with exit code -1073741819 (0xC0000005)).

The follow is my code:
```
import threading
import multiprocessing
import mitsuba as mi
def load_thread(filepath):
mi.set_variant("cuda_ad_rgb")
mi.load_file(filepath)
def load_process(filepath):
mi.set_variant("cuda_ad_rgb")
mi.load_file(filepath)
if __name__ == "__main__":
paths = "test.xml"
# multiple process works well.
# process = multiprocessing.Process(target=load_process, args=(paths, ))
# process.start()
# process.join()
# multiple thread exited with exit code -1073741819 `(0xC0000005).
thread = threading.Thread(target=load_thread, args=(paths,))
thread.start()
thread.join()
```
So i want to ask the same question: Is this parallelization possible in sionna?

**Comment by Xiaohei-Luo** [comment]
> Hello @oatuy,
> 
> For the specific error that you encountered, you can fix it by calling `mi.set_variant()` on each thread (since the Mitsuba variant is a thread-local variable). However, as @jhoydis mentioned, multiple scenes in the same process are not supported in Sionna.

Hi, Thanks for your reply.
After trying it out, I found that multiprocessing works well, but multithreading doesn't, the program exited with an exception(Process finished with exit code -1073741819 (0xC0000005)).

The follow is my code:
```
import threading
import multiprocessing
import mitsuba as mi

def load_thread(filepath):
     mi.set_variant("cuda_ad_rgb")
     mi.load_file(filepath)

def load_process(filepath):
    mi.set_variant("cuda_ad_rgb")
    mi.load_file(filepath)

if __name__ == "__main__":
    paths = "test.xml"
    # multiple process works well.
    # process = multiprocessing.Process(target=load_process, args=(paths, ))
    # process.start()
    # process.join()

    # multiple thread exited with exit code -1073741819 `(0xC0000005).
    thread = threading.Thread(target=load_thread, args=(paths,))
    thread.start()
    thread.join()
```
So i want to ask the same question: Is this parallelization possible in sionna?

**Comment by merlinND** [comment]
Hello @Xiaohei-Luo,

As discussed above, it's best to stick to `multiprocessing` or even completely separate Python processes. Note that we haven't tested either multiprocessing or multithreading ourselves, so it's not an officially supported feature.

**Comment by Xiaohei-Luo** [comment]
> Hello @Xiaohei-Luo,
> 
> As discussed above, it's best to stick to `multiprocessing` or even completely separate Python processes. Note that we haven't tested either multiprocessing or multithreading ourselves, so it's not an officially supported feature.

Thanks for the suggestion!! @merlinND
