### ISSUE TITLE
Error in Scattering Simulation Notebook

### ISSUE THREAD

**Issue by george-yammine** [NVlabs/sionna#174]
Hi! 

I tried running the RT Scattering jupyter notebook locally on my machine (M2 Pro MBP) with CPU only (LLVM 16 installed) and everything works properly until computing the paths in the last code block (Impact on Channel Impulse Response)

paths = scene.compute_paths(max_depth=5,
                            num_samples=20e6,
                            scattering=True)

I get the error: InvalidArgumentError: {{function_node __wrapped__GatherV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} indices[1,0,0,67476] = -1 is not in [0, 74) [Op:GatherV2] 

Is this a localized error to me? Thanks! 

[error.docx](https://github.com/NVlabs/sionna/files/12069590/error.docx)

**Comment by jhoydis** [comment]
Hi, I am able to reproduce this error on CPU (but running on Linux).
The error does not happen on GPU and only if scattering is enabled.
It also does not seem to happen in all scenes.
We will look into it.

**Comment by faycalaa** [comment]
Fixed by v0.15.1
