### ISSUE TITLE
AttributeError when running tutorial part 3

### ISSUE THREAD

**Issue by lkh9908** [NVlabs/sionna#176]
I am running tutorial part 3 provided in https://nvlabs.github.io/sionna/examples/Sionna_tutorial_part3.html 

And I got
AttributeError: Exception encountered when calling layer 'lmmse_equalizer' (type LMMSEEqualizer).

module 'sionna' has no attribute 'config'

at 

x_hat, no_eff = lmmse_equ([y, h_hat, err_var, no])

How should I fix it? Or is it caused by a patch update?

**Comment by jhoydis** [comment]
Hi, 

I am not able to reproduce this error.

Which version of Sionna are you using (``print(sn.__version__)``)? 

Could you run ``print(dir(sn))`` in a new cell in the notebook and copy & paste the output?

**Comment by lkh9908** [comment]
Thank you for the fase response:
print(sn.__version__):

0.15.0

print(dir(sn)):

['ALPHA_MAX', 'Config', 'DIELECTRIC_PERMITTIVITY_VACUUM', 'H', 'PI', 'SPEED_OF_LIGHT', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'channel', 'config', 'fec', 'mapping', 'mimo', 'nr', 'ofdm', 'rt', 'signal', 'utils']

And the error occurs at:
x_hat, no_eff = lmmse_equ([y, h_hat, err_var, no])

**Comment by jhoydis** [comment]
As you can see, the module sionna (imported as sn) has the property `config`.  Not sure what is going on. 
Have you tried to restart the kernel? Could you provide a minimum code example that leads to the error?

**Comment by jhoydis** [comment]
Closed due to inactivity.
