### ISSUE TITLE
Specific numpy version is required. 

### ISSUE THREAD

**Issue by karlla1220** [NVlabs/sionna#178]
I had same issue with [https://github.com/NVlabs/sionna/issues/164](https://github.com/NVlabs/sionna/issues/164). 

After comparing my python environment with google Collab, collab has numpy==1.22.4 but mine has numpy==1.24.3.

When I downgrade my numpy to 1.22.4, I seems to work as I expected, as in collab. 

Maybe some syntax makes problems between two different numpy version.

**Comment by karlla1220** [comment]
Python version was 3.10.6.

**Comment by jhtandrew** [comment]
It might be due to this expired deprecation in [NumPy 1.24.0](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations):

Ragged array creation will now always raise a ValueError unless dtype=object is passed. This includes very deeply nested sequences.

**Comment by jmoraispk** [comment]
Since the [installation](https://github.com/NVlabs/sionna/discussions/203) section of the main README says the Python version should be 3.6-3.9, I imagine the issue can be closed.

**Comment by karlla1220** [comment]
> Since the [installation](https://github.com/NVlabs/sionna/discussions/203) section of the main README says the Python version should be 3.6-3.9, I imagine the issue can be closed.

The problem is that lastest numpy requires python 3.9 or higher, so that python 3.9 would install lastest numpy based on current requirement.txt. 
Maybe it would be need to specify numpy version in requirement.txt.

**Comment by jmoraispk** [comment]
But if you have a version of Python already installed, pip won't try to upgrade to a higher version, right @karlla1220?
The requirements _assume_ that you have the pre-requirements already satisfied, which includes Python 3.6-3.9 installed. If Python is installed, then pip will install the most recent version of numpy supported for your Python version. 

But I also had a numpy problem at some point, so specifying a version would probably be the safest route.

**Comment by karlla1220** [comment]
I think we are on the same page. the problem is that "the most recent version of numpy supported" are having an issue with sionna.  

> If Python is installed, then pip will install the most recent version of numpy supported for your Python version.

Due to this problem, "pip install sionna" cannot guarantee sionna working. I also think it is safer to specify numpy version in requirement.txt.

**Comment by jhoydis** [comment]
This is has been fixed together with #164.
