### ISSUE TITLE
Using Sionna RT got ImportError: cannot import name 'Paths2CIR' from 'sionna.rt'

### ISSUE THREAD

**Issue by lkh9908** [NVlabs/sionna#184]
Watching and following the tutorial video and find this error at the import.

Is the function name changed? If so, changed to what?

Thank you

**Comment by jhoydis** [comment]
This function was renamed to [Paths.cir](https://nvlabs.github.io/sionna/api/rt.html#sionna.rt.Paths.cir) in v0.15.
