### ISSUE TITLE
Measurement of CSI-RS signal in 5G NR 

### ISSUE THREAD

**Issue by narayankusi** [NVlabs/sionna#194]
In Sionna, how can CSI-RS signal be measured in 5G NR? I want to do link level simulation to measure CSI-RS using channel CDL-C ?

**Comment by jhoydis** [comment]
Hi, currently only PUSCH is implemented. CSI-RS is for downlink.

**Comment by narayankusi** [comment]
Thank you Mr. jhoydis.  Yes, I searched for PDSCH and CSIRS but is not found. So, I have to implement in Matlab for now.
