### ISSUE TITLE
Dr Jit compilation error in Ray Tracing Example Notebook

### ISSUE THREAD

**Issue by akdd11** [NVlabs/sionna#202]
Hi,

I'm trying to follow the ray tracing example ([Ray Tracing Introduction](https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Introduction.html)) from the documentation and run into an error (see below) following the example and getting into the line where the paths are calculated.

```
# Compute propagation paths
paths = scene.compute_paths(max_depth=5,
                            num_samples=1e6)  # Number of rays shot into directions defined
                                              # by a Fibonacci spheree , too few rays can
                                              # lead to missing paths
```
Error:

```
COMPILE ERROR: failed to create pipeline
Info: Pipeline statistics
        module(s)                            :     2
        entry function(s)                    :    19
        trace call(s)                        :     3
        continuation callable call(s)        :     0
        direct callable call(s)              :     3
        basic block(s) in entry functions    :   305
        instruction(s) in entry functions    :  9681
        non-entry function(s)                :     0
        basic block(s) in non-entry functions:     0
        instruction(s) in non-entry functions:     0
        debug information                    :    no



Critical Dr.Jit compiler failure: jit_optix_check(): API error 7251 (OPTIX_ERROR_PIPELINE_LINK_ERROR): "Pipeline link error" in D:\a\drjit\drjit\ext\drjit-core\src\optix_core.cpp:392.
```

Version informations:
Sionna: 0.15.1
drjit: 0.4.2
mitsuba: 3.3.0
tensorflow: 2.10.1
Windows Server 2019

Using GPU

**Comment by jmoraispk** [comment]
Are you using WSL? 
I had a similar error when using WSL... It happened because NVIDIA OptiX doesn't support WSL yet ([source](https://forums.developer.nvidia.com/t/problem-running-optix-7-6-in-wsl/239355)).

**Comment by akdd11** [comment]
In the first try, it also had an error, but I reinstalled it and it works now without an error.

But unfortunately, the error remains the same.

**Comment by akdd11** [comment]
Sorry for the late reply, I was on vacation.

nvidia-smi gives:

- Driver Version: 536.67
- CUDA Version: 12.2

**Comment by merlinND** [comment]
Thank you. In the meantime, a new version of Mitsuba + DrJit was release. Could you please check if it fixes the issue you've encountered?

E.g. with
```
python -m pip install --upgrade mitsuba
```

**Comment by akdd11** [comment]
Hi, I updated Mitsuba (now 3.4.0) and DrJit (now 0.4.3). We also reinstalled OptiX. Regarding the support, I found nothing about major differences in OptiX support.

However, if you cannot reproduce the error and have no clue what might be the issue, feel free to close this issue. We have at least the LLVM version running :) and for now the speed is tolerable for our application.

**Comment by akdd11** [comment]
I could finally resolve issue with the help of the [issue](https://github.com/mitsuba-renderer/mitsuba3/issues/803#issuecomment-1632592565). Seems like it's a problem of old hardware (I'm using a P100), a driver downgrade to < `v535` helped finally.

**Comment by merlinND** [comment]
Thank you for reporting back @akdd11, it will be helpful for people encountering the same issue in the future!
