### ISSUE TITLE
Can't click the values when debugging in the IDE

### ISSUE THREAD

**Issue by helloGreat** [NVlabs/sionna#218]
Can't click the values of the eager tensor (e.g. b=binary_source([1000,6])) when debugging in the IDE. After clicking, the debugging breaks, which happens both in Pycharm and vscode. Maybe the memory problem of GPU?

**Comment by merlinND** [comment]
Hello @helloGreat,

I'm wondering if this is due to something specific to Sionna or rather is a general TensorFlow behavior. Have you tried reproducing this issue in a pure-Tensorflow script, without importing Sionna?

**Comment by helloGreat** [comment]
My bad! Many thanks! This is caused by the tensorflow. What can I do to see the value of tensor without transferring tensors to numpy arrays, or printing it?

**Comment by jhoydis** [comment]
Closed due to inactivity.
