### ISSUE TITLE
TensorFlow 2.6.0 tf.shape() indexing bug affect Sionna layers.

### ISSUE THREAD

**Issue by kassankar** [NVlabs/sionna#22]
**Describe the bug**
For TensorFlow version `2.6.0`, there is a bug in the indexing of the tf.shape() function. 
Please find the reference of the bug: https://github.com/tensorflow/tensorflow/issues/52571.

Some of the Sionna layer are affected by this bug, e.g. `OFDMModulator`.

**To Reproduce**
Please, find below a code to reproduce the error. (Please, make sure that the version of the tf used is `2.6.0`)
```
import tensorflow as tf
from tensorflow.keras import Model
from sionna.ofdm import OFDMModulator,OFDMDemodulator
from sionna.utils import QAMSource

class E2ESystem(Model):
    def __init__(self):
        super().__init__()
        self.cp_length = 0
        self.fft_size = 72
        self.num_ofdm_symbols = 14
        self.qam = QAMSource(4)
        self.mod = OFDMModulator(self.cp_length)

    
    @tf.function
    def call(self, batch_size):
        x_rg = self.qam([batch_size, 1, 1, self.num_ofdm_symbols, self.fft_size])
        x_time  = self.mod(x_rg)
        return x_time


e2e = E2ESystem()
e2e(128)

```

**Expected behavior**
`self.mod(x_rg)` should return the modulated signal in time. However, due to the bug an error occured.

**System:**
 - OS: [win10]
 - NVIDIA Driver version: [511.79]
 - CUDA version: [11.2]
 - Python version: [3.9.0]
 - TensorFlow version: [2.6.0]

**GPUs:**
 - Model: [QUADRO RTX 5000]
 - Memory: [16GB]

**Proposed solution**
Replace all `tf.shape()[ind]` with `Tensor.shape[ind]`
Example solution for `OFDMModulator`  layer:
-  Replace `cp = x[...,tf.shape(inputs)[-1]-self._cyclic_prefix_length:]` --> `cp = x[...,inputs.shape[-1]-self._cyclic_prefix_length:]`

**Comment by jhoydis** [comment]
Hi, does the problem persist in TF 2.7 and higher?
