### ISSUE TITLE
MAC OS GPU support

### ISSUE THREAD

**Issue by hiteshPoddar** [NVlabs/sionna#228]
I tried using the in built gpus on my mac m2 pro to run Sionna, but it doesnt work. Is it mandatory to have CUDA support? I think the MAC OS gpus dont support it.

**Comment by merlinND** [comment]
Hello @hiteshPoddar,

Both the Tensorflow and Mitsuba dependencies of Sionna require CUDA compatibility to run on the GPU.
However, you should be able to use all features on the CPU (without GPU acceleration).
If you encounter an error, could you please paste the exact code that you tried to run and the full error message?

**Comment by hiteshPoddar** [comment]
When i try to use MAC OS, as use GPUS on it, I encounter an error where the Kernel crashes unexpectedly. 
Would Sionna automatically use all the CPU cores in the system for faster execution in case there is no CUDA compatible GPU or does the user need to set some configurations explicitly to be able to use all the cores?

**Comment by merlinND** [comment]
As far as I know, all cores will be used automatically.
