### ISSUE TITLE
Question about the ray tracing example

### ISSUE THREAD

**Issue by zhiha** [NVlabs/sionna#232]
The antenna array was configured like this in example: 

```
# Configure antenna array for all transmitters
scene.tx_array = PlanarArray(num_rows=1,
                             num_cols=1,
                             vertical_spacing=0.5,
                             horizontal_spacing=0.5,
                             pattern="tr38901",
                             polarization="V")

# Configure antenna array for all receivers
scene.rx_array = PlanarArray(num_rows=1,
                             num_cols=1,
                             vertical_spacing=0.5,
                             horizontal_spacing=0.5,
                             pattern="dipole",
                             polarization="cross")

# Create transmitter
tx = Transmitter(name="tx",
                 position=[8.5,21,27])

# Add transmitter instance to scene
scene.add(tx)

# Create a receiver
rx = Receiver(name="rx",
              position=[45,90,1.5],
              orientation=[0,0,0])

# Add receiver instance to scene
scene.add(rx)

tx.look_at(rx) # Transmitter points towards receiver
```
But why the shape of the output `a` is:
```
 (1, 1, 2, 1, 1, 13, 1)
```

I mean that why the number of the array of rx is 2, not 1. I was confused that why the shape of `a` is not  (1, 1, 1, 1, 1, 13, 1).

Did I miss out on any crucial information or knowledge?

**Comment by jhoydis** [comment]
Hi,

This is the correct behaviour. 

The reason for this is that you have configured the antennas of the receive antenna array to be dual-polarized (``polarization=="cross"``). You get for both polarisation directions a different channel impulse response. If you chose single-polarized antennas, e.g., ``polarization=="V"``, then the shape of ``a`` would be as you expected.

Hope that clarifies the issue.

**Comment by zhiha** [comment]
Your answer was very clear. Thank you very much!
