### ISSUE TITLE
DNN library initialization failed

### ISSUE THREAD

**Issue by symmObserver** [NVlabs/sionna#247]
I installed Sionna using docker and tried running Discover_Sionna.ipynb. However, when I was running the part of graph execution with XLA, I encounter the error as: 
FailedPreconditionError: DNN library initialization failed. Look at the errors above for more details [Op:__inference_run_graph_xla_21694]
I searched this and this may be caused by the version compatibility between the CUDA, cuDNN and JAX. So I tried to install the correct combination and still can't figure it.

**Comment by cpyen11** [comment]
Hi @symmObserver 

Did you solve the problem? Could you please share the solution?
I followed docker-based installation then tried running Autoencoder.ipynb but got the following error message.

----------------------------------------------------------------------------------------------------------------------------
FailedPreconditionError: Exception encountered when calling layer 'e2e_system_conventional_training' (type E2ESystemConventionalTraining).

DNN library initialization failed. Look at the errors above for more details. [Op:__forward_call_1074]

Call arguments received by layer 'e2e_system_conventional_training' (type E2ESystemConventionalTraining):
  • batch_size=tf.Tensor(shape=(), dtype=int32)
  • ebno_db=tf.Tensor(shape=(128,), dtype=float32)
----------------------------------------------------------------------------------------------------------------------------
