### ISSUE TITLE
Add min_bler as stopping condition in sim_ber

### ISSUE THREAD

**Issue by nbecker** [NVlabs/sionna#251]
I have some long-running simulations and one thing that I think would be helpful is to add to sim_ber an option to stop if the BLER obtained on the last esno point is below some threshold.  For example, I am only plotting results down to 1e-5.  If the last esno point is below 1e-5 I'd like to stop rather than continuing until there are 0 block errors, to save time.

**Comment by faycalaa** [comment]
Hi,

We plan to add this feature in the next release.

**Comment by SebastianCa** [comment]
Please see #257 for further discussion.
