### ISSUE TITLE
Introducing Power Management in Sionna

### ISSUE THREAD

**Issue by suyash16999** [NVlabs/sionna#253]
Hello @jhoydis ,
I am working on Deep Learning based Channel Estimation to compare the performance with the classical methods. We would like to control the transmission power to set it at 44 dBm for the Base Station. We followed the following steps to integrate this feature-

1. Multiplied the elements of Resource Grid Mapper with a scaling factor of 5.0119 such that the average power over the RG becomes 25.118 W (44dBm)
2. Additionally we manually set the noise power to 3.163 e-13 which corresponds to -95 dBm

We were wondering how to modify the pilot signal powers as they are independently handled through the pilot pattern class and play a key role in LS Channel Estimation. Please could you guide me to introduce the correct power levels. Thanks a lot.

**Comment by SebastianCa** [comment]
Hi,
Sorry for the late response. I'm not sure if I understood the question correctly, but wouldn't it be an option to simply scale the transmitter output to fulfill the target power requirements? This would ensure that all components (data and pilot symbols) are scaled with the same factor.

Please note that this thread belongs more to the [Discussions](https://github.com/NVlabs/sionna/discussions).
