### ISSUE TITLE
Dose the simulator support self-defined MCS selection algorithm?

### ISSUE THREAD

**Issue by JackokieZhao** [NVlabs/sionna#266]
Dear sionna developer,
I found that the sionna is a greate 5G simulator in wireless communication. I am verify the performance of MCS selection algorithm. However, I can't find corresponding self-defined MCS selection tutorial and realization. So, I would appreciate it if you can tell me how to realize it.
This is a greate job!

Thanks very much!

**Comment by SebastianCa** [comment]
Hi, 
you can utilize the [select_mcs](https://nvlabs.github.io/sionna/api/nr.html#select-mcs) function to determine the `target_coderate` and `modulation_order` corresponding to a specific MCS selection. For comprehensive end-to-end performance simulations, I recommend exploring the [5G NR PUSCH Tutorial](https://nvlabs.github.io/sionna/examples/5G_NR_PUSCH.html). Please note that this threads is not an issue and would belong to the [Discussions](https://github.com/NVlabs/sionna/discussions).
