### ISSUE TITLE
Problem running the Example Notebook - 'Discover Sionna'

### ISSUE THREAD

**Issue by fayazur-mohammad** [NVlabs/sionna#27]
I am in the process of setting up the environment on Mac OS and explore Sionna using the examples provided.
The Discover Sionna notebook throws-up error half-way into the execution. I am attaching the complete pdf version of the executed notebook.
Further, I have added code in the notebook to print the version of OS, python, TensorFlow etc installed in my environment to help debugging.

Please help me setup the environment correctly. 
[Discover_Sionna-3.pdf](https://github.com/NVlabs/sionna/files/8828994/Discover_Sionna-3.pdf)

**Comment by fayazur-mohammad** [comment]
Thanks for the quick response.
1. After incorporating the above change at line 211, execution went a little ahead. However got stuck again as tensorflow-metal does not seem to be supporting DT_COMPLEX64. 
[Discover_Sionna-4.pdf](https://github.com/NVlabs/sionna/files/8837123/Discover_Sionna-4.pdf)
 True, there does not seem to be an easy fix using with tf-metal.
2. Further, am trying to run this with CPU i.e., using "with tf.device('/CPU:0'):" . However the kernel died while in monte-carlo simulation. 
[Discover_Sionna-5.pdf](https://github.com/NVlabs/sionna/files/8837124/Discover_Sionna-5.pdf)

**Comment by jhoydis** [comment]
Closed due to inactivity.
