### ISSUE TITLE
The problem of interpreting of Impulse Response Results Generated by Ray Tracing

### ISSUE THREAD

**Issue by Virusx51** [NVlabs/sionna#277]
I am running a ray tracing script to compute the impulse response in accordance with the example provided in the Sionna documentation.

With the current parameters max_depth=4, num_samples=2e6, the results exhibit peaks with similar trajectories. Which parameters should be adjusted to eliminate adjacent rays with closely matching trajectories?
I understand that the impulse response is measured in volts, however it is unclear where the transmitter power is set in the model. What signal attenuation model is used during ray tracing? Varying the radiation pattern parameter pattern resulted in the following direct ray visibility values: around 100 for pattern="dipole", and around 210 for pattern="tr38901". Clarification on the interpretation of these parameters would be appreciated.
Thank you in advance.
![image](https://github.com/NVlabs/sionna/assets/71511652/1af2888f-4f7a-4de6-b2b2-da7e4bf2d2cd)
![image](https://github.com/NVlabs/sionna/assets/71511652/ea5c07c7-5958-403e-b117-975c89bf1d65)
[](![image](https://github.com/NVlabs/sionna/assets/71511652/a643179b-77e0-4ec6-a538-79ab09c372d2))

```python
scene = load_scene(files[1]) # Try also sionna.rt.scene.etoile

# Configure antenna array for all transmitters
scene.tx_array = PlanarArray(num_rows=1,
                             num_cols=1,
                             vertical_spacing=0.5,
                             horizontal_spacing=0.5,
                             pattern="tr38901",
                             polarization="V")

# Configure antenna array for all receivers
scene.rx_array = PlanarArray(num_rows=1,
                             num_cols=1,
                             vertical_spacing=0.5,
                             horizontal_spacing=0.5,
                             pattern="dipole",
                             polarization="cross")

# Create transmitter
tx = Transmitter(name="tx",
                 position=[-206.7,-19.14,31])
# [-206.7,-19.14,31]
# [-111,-66.02,2]
# Add transmitter instance to scene
scene.add(tx)

# Create a receiver
rx = Receiver(name="rx",
              position=[-111,-66.02,2],
              orientation=[0,0,0])

# Add receiver instance to scene
scene.add(rx)

tx.look_at(rx) # Transmitter points towards receiver

scene.frequency = 2.14e9 # in Hz; implicitly updates RadioMaterials

scene.synthetic_array = True # If set to False, ray tracing will be done per antenna element (slower for large arrays)
so = scene.get('Altes_Rathaus-itu_concrete')
# Compute propagation paths
paths = scene.compute_paths(max_depth=4,
                            num_samples=2e6)  # Number of rays shot into directions defined
                                              # by a Fibonacci spheree , too few rays can
                                              # lead to missing paths

# Visualize paths in the 3D preview
if colab_compat:
    scene.render("my_cam", paths=paths, show_devices=True, show_paths=True, resolution=resolution);
    raise ExitCell
scene.preview(paths, show_devices=True, show_paths=True) # Use the mouse to focus on the visualized paths
scene.compute_paths()
# Default parameters in the PUSCHConfig
subcarrier_spacing = 15e3
fft_size = 48
# Print shape of channel coefficients before the application of Doppler shifts
# The last dimension corresponds to the number of time steps which defaults to one
# as there is no mobility
print("Shape of `a` before applying Doppler shifts: ", paths.a.shape)

# Apply Doppler shifts
paths.apply_doppler(sampling_frequency=subcarrier_spacing, # Set to 15e3 Hz
                    num_time_steps=14, # Number of OFDM symbols
                    tx_velocities=[3.,0,0], # We can set additional tx speeds
                    rx_velocities=[0,7.,0]) # Or rx speeds

print("Shape of `a` after applying Doppler shifts: ", paths.a.shape)

a, tau = paths.cir()
# p2c = Paths2CIR(sampling_frequency=100e6, scene)

print("Shape of tau: ", tau.shape)
# Print shape of channel coefficients before the application of Doppler shifts
# The last dimension corresponds to the number of time steps which defaults to one
# as there is no mobility
print("Shape of `a` before applying Doppler shifts: ", paths.a.shape)

# Apply Doppler shifts
paths.apply_doppler(sampling_frequency=subcarrier_spacing, # Set to 15e3 Hz
                    num_time_steps=14, # Number of OFDM symbols
                    tx_velocities=[3.,0,0], # We can set additional tx speeds
                    rx_velocities=[0,7.,0]) # Or rx speeds

print("Shape of `a` after applying Doppler shifts: ", paths.a.shape)

a, tau = paths.cir()
# p2c = Paths2CIR(sampling_frequency=100e6, scene)

print("Shape of tau: ", tau.shape)
```

**Comment by jeertmans** [comment]
Hello,

I will try to answer, but having the code that generated those slides would help :-)

> With the current parameters max_depth=4, num_samples=2e6, the results exhibit peaks with similar trajectories. Which parameters should be adjusted to eliminate adjacent rays with closely matching trajectories?

Are you sure those paths are the same? This is quite common to have paths with similar lengths but different powers, especially if you include diffraction. Thus, you can have two paths with similar length, but one containing a diffraction (instead of a reflection) which explains the large difference in received signal power.

> What signal attenuation model is used during ray tracing?
It depends on the type of interaction. It is quite well explained in the [EM Primer](https://nvlabs.github.io/sionna/em_primer.html), but you can also take a look at the code, like those lines (and around):

https://github.com/NVlabs/sionna/blob/fd8b13a092d65053f3225c4c0ccb88aedfc44f5b/sionna/rt/solver_paths.py#L869-L878

**Comment by faycalaa** [comment]
Hi,

- Sionna does not discard paths if they are not occluded. You can reduce the number of generated paths by either reducing the number of samples (`num_samples`) or, if you are using scattering, by reducing `scat_keep_prob`.This however could lead to missing paths that contribute significantly to the channel impulse response. Note that the visualization of paths using [preview()](https://nvlabs.github.io/sionna/api/rt.html?highlight=compute_paths#sionna.rt.Scene.preview) or [render()](https://nvlabs.github.io/sionna/api/rt.html?highlight=compute_paths#sionna.rt.Scene.render) shows all traced paths, regardless of their amplitude.

- The channel impulse response computed by the ray tracer is independent of the transmit power. It carries information about the attenuation of the signal, and you would need to scale the channel impulse response according to the transmit power.

- The number of paths traced does not depend on the antenna pattern. Note that if you are using scattering, paths can be randomly discarded if `scat_keep_prob` is set to a value lower than 1.

Hope this helps.

**Comment by Virusx51** [comment]
Thank you very much, I figured out the issue.
