### ISSUE TITLE
Can't add custom scene in Sionna

### ISSUE THREAD

**Issue by anindha-dhar** [NVlabs/sionna#280]
While I am trying to add a new XML custom scene, the error is showing:

![image](https://github.com/NVlabs/sionna/assets/66663552/a0744370-39d7-4c45-ba1c-2c8ae7ec6267)

**Comment by merlinND** [comment]
Hello @anindha-dhar,

It looks like the mesh(es) referred to by your scene `buet.xml` are not located in a standard location. Typically, if your scene XML file refers to "Plane.ply", then that file should be placed right next to the XML file.

**Comment by anindha-dhar** [comment]
> Hello @anindha-dhar,
> 
> It looks like the mesh(es) referred to by your scene `buet.xml` are not located in a standard location. Typically, if your scene XML file refers to "Plane.ply", then that file should be placed right next to the XML file.

Thanks it works !
