### ISSUE TITLE
Can't visualize the path in 3D preview

### ISSUE THREAD

**Issue by anindha-dhar** [NVlabs/sionna#281]
While I'm trying to visualize the path, the following error occurs:
![image](https://github.com/NVlabs/sionna/assets/66663552/33ad3694-ad50-4dd6-a2de-f45ade58d7bd)

**Comment by SebastianCa** [comment]
Hi,
it is difficult to identify the issue without knowing the rest of your code. Could you please provide a minimum code example to reproduce the error?

A quick check to see if your setup is correctly configured is to run the [SionnaRT Tutorial](https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Introduction.html).
