### ISSUE TITLE
Python Kernel Crashing with GPU support

### ISSUE THREAD

**Issue by manideepabc** [NVlabs/sionna#289]
### Discussed in https://github.com/NVlabs/sionna/discussions/285

<div type='discussions-op-text'>

<sup>Originally posted by **manideepabc** December 12, 2023</sup>
Hello,

I am trying to run the tutorial example Ray tracing part 1 using GPU support in the docker container. I see that the Python kernel crashes as soon as I try to load the scene. But everything works fine when using the CPU to run the code. Did anyone face this problem while running it? Can someone help us with this?

We pretty much used the DOCKERFILE and Makefile provided in the repository and haven't changed any Python versions while running the sample codes.

What have I tried?:  We tried to see if this issue persists while running other code samples. So, we tried running the Realistic Multiuser MIMO channel code with GPU support, and it worked perfectly. We ensured that it ran on GPU by observing that the GPU utilization has increased when running with GPU support.</div>

**Comment by Slond** [comment]
Have same problem (didn't solve, just use CPU), I think, that it's connected with deprecated nvidia-docker library

**Comment by merlinND** [comment]
Closing as duplicate since discussion in ongoing in #285.
