### ISSUE TITLE
Installation issues 

### ISSUE THREAD

**Issue by harish-ramchandran** [NVlabs/sionna#292]
```
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: jit_init_thread_state(): the LLVM backend is inactive because the LLVM shared library ("libLLVM.so") could not be found! Set the DRJIT_LIBLLVM_PATH environment variable to specify its path.
```

Can anybody help to fix this error ?

After pip install sionna, I am inside python and when I do import sionna - I see the following errors

**Comment by jhoydis** [comment]
It seems that you are running Sionna on CPU. Did you install LLVM as mentioned in the [Installation Guide](https://nvlabs.github.io/sionna/installation.html)?
You can also search for past issues around LLVM (e.g., #223 or #107) and see if one of them is helpful to you.

**Comment by jdelancey** [comment]
I ran into something similar with my Mitsuba/DrJit install and found [this DrJit issue](https://github.com/mitsuba-renderer/drjit/issues/196) to be helpful. I added [a comment](https://github.com/mitsuba-renderer/drjit/issues/196#issuecomment-1836434550) about needing to roll back to an older version of LLVM, which fixed the issue for me. Also, please note that the environment variable DRJIT_LIBLLVM_PATH needs to be the path to libLLVM.so, **not** the directory containing the binary. This was true on Windows, and I assume the behavior is the same on Linux. I advise trying both after downgrading your LLVM version as recommended in the linked comments.

**Comment by harish-ramchandran** [comment]
Thank you both. The LLVM library was not installed properly. I also was not setting the path for the DRJIT_LIBLLVM_PATH correctly.
I was able to get this sorted out and am able to run Sionna now. Thanks. Closing this this issue now
