### ISSUE TITLE
Exploring Channel Impulse Responses in Sionna: Moving Beyond Free Space Path Loss

### ISSUE THREAD

**Issue by Virusx51** [NVlabs/sionna#294]
Hello,
I have the following question. After scene-based tracing, I have channel coefficients and delays for each ray. As I understand it, the signal attenuation model used during tracing is the free space path loss. I would like to use other models, such as Uma. The Sionna documentation states that:

> Propagation Paths can be transformed into time-varying channel impulse responses (CIRs) via cir(). The CIRs can then be used for link-level simulations in Sionna via the functions cir_to_time_channel() or cir_to_ofdm_channel(). Alternatively, you can create a dataset of CIRs that can be used by a channel model with the help of CIRDataset.

I'm not quite sure how to retrieve the impulse response. Is it possible to do this? Please help. Thank you in advance!

**Comment by jhoydis** [comment]
Hi,

Please have a look at this [tutorial](https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Introduction.html#From-Paths-to-Channel-Impulse-Responses) with regards to your question about retrieving channel impulse responses. 

It does not make sense to apply a different path loss model to ray-traced channel impulse responses as these already include a distanced-based path loss as well as additional attenuations from reflection, diffraction, and antenna patterns. UMa is a stochastic geometry-based channel model.

**Comment by Virusx51** [comment]
Thank you very much for the response!
