### ISSUE TITLE
Receiver antenna height for coverage map

### ISSUE THREAD

**Issue by w1ex** [NVlabs/sionna#299]
Hello,

I want to adjust the receiver antenna height when calculating coverage map. 
Could you tell me on how to set it, or point me to the relevant section in the documentation if I've missed it?

Thank you for your time and assistance.

**Comment by faycalaa** [comment]
Hi,

When calling [Scene.coverage_map()](https://nvlabs.github.io/sionna/api/rt.html?highlight=coverage_map#sionna.rt.Scene.coverage_map), you can set the position of the center of the coverage map `(x,y,z)` using the `cm_center` argument, where `z` controls the elevation.

**Comment by w1ex** [comment]
Thank you very much!
