### ISSUE TITLE
Support for PyTorch

### ISSUE THREAD

**Issue by taha-yassine** [NVlabs/sionna#3]
This project is awesome and opens the doors to many opportunities.
I was wondering if support for PyTorch was something you thought about. PyTorch is well-established in the academic world and most code accompanying deep learning papers uses it instead of TF. On the other hand, TF is greatly used in production environments.
I don't know how much complexity would supporting PyTorch add to the project, but could we imagine that some day it could happen? And are you accepting contributions in this regard?

**Comment by jhoydis** [comment]
Thank you for this question!

Please note that each component of Sionna is a Keras layer which allows us to benefit from the very elegant high-level Keras API. While TensorFlow 2 and PyTorch have very similar capabilities and syntax, there is no standard high-level interface like Keras for PyTorch, yet. This has been one of the reasons for choosing TensorFlow over PyTorch. 

We hence do not accept PyTorch-related contributions.

**Comment by MrCrHaM** [comment]
> This has been one of the reasons for choosing TensorFlow over PyTorch.
@jhoydis Thank you for the explanation. Could you please elaborate a bit on other reasons for choosing TensorFlow over PyTorch? Is there any performance reason?
