### ISSUE TITLE
validation and add new scenarios

### ISSUE THREAD

**Issue by eekarot** [NVlabs/sionna#31]
1. The tdlb channel we verified is quite different from that TS38.901, as shown in the following figure.
![image](https://user-images.githubusercontent.com/32899980/174559307-dd96f995-3442-4462-b1b3-a531121eb0c9.png)

2. In UMI, UMA and RMA scenarios, the validation results of batch size=400000 and 500000 are quite different. How to set this parameters

3. I wonder is there a plan to add an indoor office scenarios.

**Comment by faycalaa** [comment]
Hi,

Could you please share code snippets for reproducing 1 and 2? You could use Gist for that.

Concerning 3, it is planned to add the indoor office and indoor factory scenarios to Sionna. There is however no clear timeline for the release of these features yet.

**Comment by jhoydis** [comment]
Closed due to inactivity.
