### ISSUE TITLE
Bug_with_scene.synthetic_array 

### ISSUE THREAD

**Issue by MattiaP1999** [NVlabs/sionna#310]
Hello,
I created a LOS scenario (max_depth=0) with 1 TX and a uniform linear array in RX (isotropic sources and vertically polarized).  When using scene.synthetic_array  = False I obtain wrong results for the "a" coefficients, while with the plane wave assumption (scene.synthetic_array  = True) I obtain what I expect for my scenario. Moreover, I tried to insert single element RX antennas at the positions where Sionna automatically positions the RX array antennas, the results are plausible and similar with the plane wave assumption. [Here ](https://unipdit-my.sharepoint.com/:p:/g/personal/mattia_piana_studenti_unipd_it/EZDH9-8a6DpEkZuzK7JeF3kB4Jc7d1SHHNJ96CPP_hfsmg?e=HINvya)I made a presentation describing what I tried to do. 
Thanks in advance for the reply,
Mattia

**Comment by jhoydis** [comment]
Hi,

Have you looked at the path delays as well? 
For a synthetic array the delay is for all paths the same and the phase offset is already part of the channel coefficients.
For the non-synthetic array, this is not the case and each antenna will see a different delay. When you translate the delays to the resulting phase shifts, you should get identical behaviour. We have some unit tests for exactly this case:

See line 144 in this file: https://github.com/NVlabs/sionna/blob/main/test/unit/rt/test_antenna_array.py

Hope that solves your problem.

**Comment by jhoydis** [comment]
Closed due to inactivity.
