### ISSUE TITLE
Is is possible to increase the result paths in compute_paths?

### ISSUE THREAD

**Issue by w1ex** [NVlabs/sionna#318]
Hello, 

I have adjusted the num_samples in sionna.rt.Scene.compute_paths and conducted tests in several scenes (scattering and diffraction are true). However, I observed no difference in the number of paths in the results when comparing num_samples=1e6 and 1e8. Is there a method to increase the number of path in result?

Thank you.

**Comment by faycalaa** [comment]
Hi,

There should be more scattered paths when `num_samples` is increased and `scat_keep_prob` is set to a value higher than 0. Note that the scattering coefficients of the radio materials should be set to a value higher than 0 to ensure that the scattered paths carry energy.

If that's not helping, could you share a code snippet that reproduces the issue?

**Comment by w1ex** [comment]
Oh, I just noticed that I wrongly set scat_keep_prob to 0. 
Thank you very much!
