### ISSUE TITLE
OFDM_rg multi-users sends over all resource elements, but this isn't practical!

### ISSUE THREAD

**Issue by abdallah1097** [NVlabs/sionna#336]
Regarding the OFDM resource grid with multiple users in the environment, typically not all users use the entire resource grid, instead, each user is assigned a certain subcarrier (FDMA) for instance. 

But by default, the resource grid assigns a resource grid for each user, and allows all users to use the entire grid which is not practical. Do we get to set each user a certain Subcarrier?

**Comment by jhoydis** [comment]
In this case you would need to define for every user a different resource grid.

**Comment by abdallah1097** [comment]
@jhoydis  assume I want to use FDMA with OFDM (Each user gets a subcarrier to send on). Can you illustrate what parameters to be changed per resource grid?

**Comment by jhoydis** [comment]
I do not know what your full simulation setup is and what you are trying to accomplish.

As a general comment, from a simulation point of view, it does probably not make sense to simulate many users on non-overlapping subcarriers. Because the subcarriers are all statistically the same, it would be sufficient to simulate a single user. 

However, if you really wanted to isolate users on different parts of the spectrum, you could simply set the left and right guard carriers via ``num_guard_carriers`` for each resource grid in such a way that they do not interfere.

**Comment by abdallah1097** [comment]
@jhoydis  Thank you for your fast response and this significant simulator. I think we should add FDMA or TDMA option in the resource grid instance, I'll contribute this  with PR ASAP. Thanks a lot

**Comment by abdallah1097** [comment]
@jhoydis  I implemented multiple resource grid but can I get help with this error:

`
line 319, in update_env_States
    self.b_hat = self._decoder(llr)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/sionna/fec/ldpc/decoding.py", line 1246, in build
    assert (input_shape[-1]==self.encoder.n), \
AssertionError: Last dimension must be of length n.
`

The way I implemented this is I created list of resource grid elements, and did the mapping in a loop. However, I had to change the encoder since the rg.num_data_symbols is now smaller. The encoder and decoder use "temp_rg" which is a created grid mapper for users, but the lmmse channel estimator takes the large resource grid (self._rg) since I append:

`
class CommunicationEnv(gym.Env):
    def __init__(self):
        # Read hyperparameters from YAML file
        with open('hyp.yaml', 'r') as file:
            hyperparameters = yaml.safe_load(file)

        self.cpu_name = "CPU:0" # tf.config.list_physical_devices('CPU')[0].name
        print(f"[device.name for device in devices]: {self.cpu_name}")

        # Defining Environment Attributes
        self._scenario = hyperparameters['scenario'] # One of ["umi", "uma", "rma"]
        self._perfect_csi = hyperparameters['perfect_csi'] # if True, No channel estimation is needed
        self.batch_size = hyperparameters['batch_size']
        self._power_range_start = hyperparameters['power_range_start']
        self._power_range_end = hyperparameters['power_range_end']
        self._power_range_step = hyperparameters['power_range_step']
        self.alpha = hyperparameters['alpha'] # Factor for the reward of other user's capacity

        # Internally set parameters
        self._carrier_frequency = hyperparameters['carrier_frequency']
        self._fft_size = hyperparameters['fft_size']
        self._subcarrier_spacing = hyperparameters['subcarrier_spacing']
        self._num_ofdm_symbols = hyperparameters['num_ofdm_symbols']
        self._cyclic_prefix_length = hyperparameters['cyclic_prefix_length']
        self._pilot_ofdm_symbol_indices = hyperparameters['pilot_ofdm_symbol_indices']
        self._num_bs_ant = hyperparameters['num_bs_ant']
        self.num_ut = hyperparameters['num_ut']
        self._num_ut_ant = hyperparameters['num_ut_ant']
        self._num_bits_per_symbol = hyperparameters['num_bits_per_symbol']
        
        self._use_LPDC = hyperparameters['use_LPDC']
        if self._use_LPDC:
            self._coderate = hyperparameters['coderate']
        else:
            self._coderate = 1.0

        # Create an RX-TX association matrix
        # rx_tx_association[i,j]=1 means that receiver i gets at least one stream from transmitter j. Depending on the transmission direction (uplink or downlink),
        # the role of UT and BS can change.
        bs_ut_association = np.zeros([1, self.num_ut])
        bs_ut_association[0, :] = 1
        self._rx_tx_association = bs_ut_association
        self._num_tx = self.num_ut
        self._num_streams_per_tx = self._num_ut_ant

        # There will be a general OFDM Resource Grid to be used in estimation and everything in the Base Station
        self._rg = ResourceGrid(num_ofdm_symbols=self._num_ofdm_symbols,
                                fft_size=self._fft_size,
                                subcarrier_spacing=self._subcarrier_spacing,
                                num_tx=self._num_tx,
                                num_streams_per_tx=self._num_streams_per_tx,
                                cyclic_prefix_length=self._cyclic_prefix_length,
                                pilot_pattern="kronecker",
                                pilot_ofdm_symbol_indices=self._pilot_ofdm_symbol_indices) 
        # Shape :[num_tx, num_streams_per_tx, num_ofdm_symbols, fft_size]
        assert self._rg.build_type_grid().shape == (self.num_ut, self._num_streams_per_tx, self._num_ofdm_symbols, self._fft_size)

        # Setup StreamManagement
        self._sm = StreamManagement(self._rx_tx_association, self._num_streams_per_tx)

        # Configure antenna arrays
        self._ut_array = AntennaArray(
                                 num_rows=1,
                                 num_cols=1,
                                 polarization="single",
                                 polarization_type="V",
                                 antenna_pattern="omni",
                                 carrier_frequency=self._carrier_frequency)

        self._bs_array = AntennaArray(num_rows=1,
                                      num_cols=int(self._num_bs_ant/2),
                                      polarization="dual",
                                      polarization_type="cross",
                                      antenna_pattern="38.901",
                                      carrier_frequency=self._carrier_frequency)
        
        # Configure the channel model
        self._channel_models_list = ['umi'] # ['umi', 'uma', 'rma']
        self._scenario = random.choice(self._channel_models_list)
        if self._scenario == "umi":
            self._channel_model = UMi(carrier_frequency=self._carrier_frequency,
                                      o2i_model="low",
                                      ut_array=self._ut_array,
                                      bs_array=self._bs_array,
                                      direction="uplink",
                                      enable_pathloss=True,
                                      enable_shadow_fading=True)
        elif self._scenario == "uma":
            self._channel_model = UMa(carrier_frequency=self._carrier_frequency,
                                      o2i_model="low",
                                      ut_array=self._ut_array,
                                      bs_array=self._bs_array,
                                      direction="uplink",
                                      enable_pathloss=True,
                                      enable_shadow_fading=True)
        elif self._scenario == "rma":
            self._channel_model = RMa(carrier_frequency=self._carrier_frequency,
                                      ut_array=self._ut_array,
                                      bs_array=self._bs_array,
                                      direction="uplink",
                                      enable_pathloss=True,
                                      enable_shadow_fading=True)

        # Instantiate other building blocks
        self._binary_source = BinarySource()
        self._qam_source = QAMSource(self._num_bits_per_symbol)

        # Create an OFDM Resource Grid for each user [CDMA]
        # For each user, we'll use a masked grids and then we concatenate
        self._rg__mapper_list = []
        self.num_subcarriers_per_user = int(self._fft_size // self._num_tx)
        for i in range(self.num_ut):
            temp_rg = ResourceGrid(num_ofdm_symbols=self._num_ofdm_symbols,
                                    fft_size=self._fft_size,
                                    subcarrier_spacing=self._subcarrier_spacing,
                                    num_tx=1, # self._num_tx
                                    num_streams_per_tx=self._num_streams_per_tx,
                                    cyclic_prefix_length=self._cyclic_prefix_length,
                                    pilot_pattern="kronecker",
                                    pilot_ofdm_symbol_indices=self._pilot_ofdm_symbol_indices,
                                    num_guard_carriers = [i*self.num_subcarriers_per_user, (self.num_ut-i-1)*(self.num_subcarriers_per_user)])
            # Shape :[1, num_streams_per_tx, num_ofdm_symbols, fft_size]
            assert temp_rg.build_type_grid().shape == (1, self._num_streams_per_tx, self._num_ofdm_symbols, self._fft_size)
            fig = temp_rg.show()
            fig.savefig(os.path.join('users_grids', f'fig_{i}.png'))
            # plt.show()
            self._rg__mapper_list.append(ResourceGridMapper(temp_rg))
        
        assert self._rg.num_data_symbols != temp_rg.num_data_symbols
        self._n = int(self._rg.num_data_symbols*self._num_bits_per_symbol) # Number of coded bits
        self._k = int(self._n*self._coderate)                              # Number of information bits
    
        self._n_user = int(temp_rg.num_data_symbols*self._num_bits_per_symbol) # Number of coded bits
        self._k_user = int(self._n_user*self._coderate)                              # Number of information bits

        if self._use_LPDC:
            self._encoder = LDPC5GEncoder(self._k_user, self._n_user)
            self._decoder = LDPC5GDecoder(self._encoder)

        self._mapper = Mapper("qam", self._num_bits_per_symbol)

        self._ofdm_channel = OFDMChannel(self._channel_model, self._rg, add_awgn=True,
                                         normalize_channel=True, return_channel=True)

        self._remove_nulled_subcarriers = RemoveNulledSubcarriers(self._rg)
        self._ls_est =  LSChannelEstimator(self._rg, interpolation_type="nn")
        self._lmmse_equ = LMMSEEqualizer(self._rg, self._sm)
        self._demapper = Demapper("app", "qam", self._num_bits_per_symbol)

        # Define Observation Space
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(16,28674))

        # Set initial parameters
        self._previous_tx_power = np.array([1]*self.num_ut)
        self._previous_channel_gain = np.ones((self.num_ut*self._num_streams_per_tx, self.batch_size*1*self._num_bs_ant*self._num_ofdm_symbols*self._fft_size))

        # Define Action Space
        power_multiplicitive_factors = np.arange(self._power_range_start, self._power_range_end+self._power_range_step, self._power_range_step).round(1).tolist() # Multiplcitive of 1's
        self.action_space = spaces.Discrete(len(power_multiplicitive_factors))

        self._action_to_transmit_power = {}
        for index, value in enumerate(power_multiplicitive_factors):
            self._action_to_transmit_power[index] = value
            
        print(f"Action Space is: {self.action_space}, Mapping: {self._action_to_transmit_power}")

        # No is a constant, we change the transmit power
        self.no = ebnodb2no(-84, self._num_bits_per_symbol, self._coderate, self._rg) # The noise is as same as the power -114 dbm -> 10^-11.4 watts -> -84 dB

        # Initialize the environment
        self.reset()
`
The function implementation that takes one step in the environment:
`    def update_env_States(self, actions_list=None):
        """
        Runs an entire step through the environment from Tx's to Rx
        """
        with tf.device(self.cpu_name):            
            # Setting New Topology for users
            self.new_topology()
            
            self.b = self._binary_source([self.batch_size, self._num_tx, self._num_streams_per_tx, self._k_user]) # Sent bits

            if self._use_LPDC:
                c = self._encoder(self.b) # Sent Codeword: Encoded bits
            else:
                c = self.b

            x = self._mapper(c) # Sent Symbols

            # Create an nan numpy array
            x_rg_numpy = np.full((self.batch_size, self.num_ut, self._num_streams_per_tx, self._num_ofdm_symbols, self._fft_size), np.nan, dtype=np.complex64)

            # Loop over users, map throught channel with custom power
            for i in range(self.num_ut):
                added_input = self._rg__mapper_list[i](tf.expand_dims(x[:,i,:,:], axis=1)) # Mapped OFDM Grid
                x_rg_numpy[:, i, :, :, :] = added_input[:,0, :, :, :]
                # assert len(actions_list) == x_rg_numpy.shape[1], f"len(actions_list): {len(actions_list)}, x_rg_numpy.shape[1]: {x_rg_numpy.shape[1]}"
            
            assert not np.any(np.isnan(x_rg_numpy)), f"There are still empty elements in the array: {np.isnan(x_rg_numpy)}"
            x_rg = tf.convert_to_tensor(x_rg_numpy) # TODO: complex32
            y, h = self._ofdm_channel([x_rg, self.no])

            if self._perfect_csi:
                h_hat = self._remove_nulled_subcarriers(h)
                err_var = 0.0
            else:
                h_hat, err_var = self._ls_est([y, self.no])

            x_hat, no_eff = self._lmmse_equ([y, h_hat, err_var, self.no])

            llr = self._demapper([x_hat, no_eff])

            if self._use_LPDC:
                self.b_hat = self._decoder(llr)
            else:
                self.b_hat = llr
            
            assert self.b_hat.shape == self.b.shape, f"b_hat shape: {self.b_hat.shape}, b shape {self.b.shape}"

        return actions_list, h_hat`
        
Can you help me with this?

**Comment by AWallyAllah** [comment]
Any updates @jhoydis ?
