### ISSUE TITLE
Use Frequency-division multiplexing (FDM) or Code-division Multiplexing (CDM)

### ISSUE THREAD

**Issue by abdallah1097** [NVlabs/sionna#341]
It is not practical for all users in the sector to send over all sub-carriers in the grid. 

1. Isn't there a method to implement FDM where each user gets assigned a range of sub-carries to send over?
2. Isn't there a method to implement CDM where all users send over all sub-carriers, but each user gets assigned a code?

**Comment by SebastianCa** [comment]
This issue appears to be a duplicate of question #342 in discussions. Please refer to #342 for further discussions.
