### ISSUE TITLE
Resource exhausted error: when allocating tensor with shape[324937,4096,3,1]

### ISSUE THREAD

**Issue by weirdooo-18** [NVlabs/sionna#345]
I was just trying to experiment with Sionna for a larger transmitter configuration of 64 x 64 (cross polarized). The number of rows and columns in the receiver array is kept as 1. And, I have 10 such receivers placed at random locations. If the num_samples is kept in the range of 10e2 to 10e4, i have no issues. But if i increase the value to 10e5 or higher, I end up getting ResourceExhaustedError, in which a very large number ends up coming as the shape of a tensor. Can someone plsss help????
![55555](https://github.com/NVlabs/sionna/assets/161753847/0c3c35c5-a96a-420b-b871-c0fc54a38e2d)

**Comment by anilgurses** [comment]
Your GPU simply doesn't have enough resources to handle the requested operation. You either need to reduce the num_samples or run it on a more capable GPU (more GPU memory). I hope this helps.

**Comment by weirdooo-18** [comment]
Will reducing the num_samples affect the other parameters in any way? Or does it determine only the quality of the scene?

**Comment by SebastianCa** [comment]
As pointed out by @anilgurses, this issue can be solved by either reducing the `num_samples` or increasing the available memory resources.
