### ISSUE TITLE
100% RAM usage for large batch simulation (simulation ends up CRASHING)

### ISSUE THREAD

**Issue by pablosreyero** [NVlabs/sionna#349]
Dear Sionna community,

I've been playing around with this tutorial: https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Introduction.html for quite a while. 

The thing is that after computing in a `for` loop: `y = channel([x, h_freq, no])`, `b_hat = pusch_receiver([y, no])` , `BER = compute_ber(b, b_hat).numpy()` for several iterations, I run out of memory. The problem is that the RAM memory slowly fades away as the number of iterations increases and this forces the kernel to die, because I run out of memory. Therefore, If I set a batch of 100000 iterations, the simulation never gets to finish and we usually only reach 56000 iterations (approx)

I have noticed this behaviour not only for the functions mentioned above inside a `for`, but also for the Ray-Tracing part in a whole (also inside a `for` loop), i.e., load scene, deploy Tx and Rx, compute paths and CIRs. 

I am running Sionna in a docker container, which is currently running in a machine with the following specifications:

- Ubuntu 20.04 LTS
- Intel® Xeon(R) Silver 4309Y CPU @ 2.80GHz × 32
- 64 GB of RAM

Here's the code to reproduce this issue: 

[LongBatchCode.zip](https://github.com/NVlabs/sionna/files/14523621/LongBatchCode.zip)

Any feedback will be appreciated, thanks in advance!

Pablo.-

**Comment by merlinND** [comment]
Hello @pablosreyero,

Could you try structuring your code in the following way and let us know if the problem still occurs:

```py
import gc

def iteration(...):
    y = channel([x, h_freq, no])
    b_hat = pusch_receiver([y, no]) 
    BER = compute_ber(b, b_hat)
    return BER.numpy()

def main():
    for it_i in range(...):
        BER_np = iteration(...)
        gc.collect()
```

If this works, you can call the garbage collector less often to reduce the overhead (e.g. once every 500 iterations).

**Comment by pablosreyero** [comment]
Hello @merlinND,
 
Thank you very much for your reply. We have already tested both the garbage collector and the `del` statement with multiple variables in the past, but it did not help out. However, I reproduced the exact same code structure you have provided, and I obtained the same results. I attach the new code and a log file with the evolution of the RAM (memory-wise) in the `zip` file.
 
Thanks again for your help.
 
Pablo.-

https://github.com/NVlabs/sionna/files/14603871/files.zip

**Comment by pablosreyero** [comment]
> Hello @pablosreyero,
> 
> Could you try structuring your code in the following way and let us know if the problem still occurs:
> 
> ```python
> import gc
> 
> def iteration(...):
>     y = channel([x, h_freq, no])
>     b_hat = pusch_receiver([y, no]) 
>     BER = compute_ber(b, b_hat)
>     return BER.numpy()
> 
> def main():
>     for it_i in range(...):
>         BER_np = iteration(...)
>         # Use BER_np as needed
> 
>         del BER_np
>         gc.collect()
> ```
> 
> The key thing is that all per-iteration variables must go out of scope before calling the garbage collector.
> 
> If this works, you can call the garbage collector less often to reduce the overhead (e.g. once every 500 iterations).

Hello @merlinND,
 
Thank you very much for your reply. We have already tested both the garbage collector and the `del` statement with multiple variables in the past, but it did not help out. However, I reproduced the exact same code structure you have provided, and I obtained the same results. I attach the new code and a log file with the evolution of the RAM (memory-wise) in the `zip` file.
 
Thanks again for your help.
 
Pablo.-

https://github.com/NVlabs/sionna/files/14603871/files.zip

**Comment by jhoydis** [comment]
Have you tried running your simulations in graph mode?

**Comment by pablosreyero** [comment]
> Have you tried running your simulations in graph mode?

Not yet, but I'm going to do so. I'll let you know if we encounter any other errors.

**Comment by SebastianCa** [comment]
Closed due to inactivity.
