### ISSUE TITLE
llvm init issue after update fedora38->fedora39

### ISSUE THREAD

**Issue by nbecker** [NVlabs/sionna#365]
I had a working sionna setup on fedora38.  After update to fedora39 I get:
```
jit_llvm_init(): detected LLVM version lacks critical functionality, shutting down LLVM backend..
```
Any ideas how to debug this?  I have a number of llvm libaries:
```
llvm-libs-17.0.6-3.fc39.x86_64
llvm16-libs-16.0.6-5.fc39.x86_64
llvm15-libs-15.0.7-4.fc39.x86_64
llvm-static-17.0.6-3.fc39.x86_64
llvm-17.0.6-3.fc39.x86_64
llvm-test-17.0.6-3.fc39.x86_64
llvm-googletest-17.0.6-3.fc39.x86_64
llvm-devel-17.0.6-3.fc39.x86_64
```

**Comment by merlinND** [comment]
Hello @nbecker,

First, are you relying on the LLVM backend or are you using a CUDA GPU?
If you are using the CUDA backend, then this warning can be ignored.

I don't know much about Fedora and what default paths it uses, so I'm not sure which LLVM version is getting picked up. You can specify one explicitly using the `DRJIT_LIBLLVM_PATH` environment variable.

**Comment by nbecker** [comment]
I am relying on CUDA GPU.  After installing various cuda libraries I get this when running my test code:
```
 ./32apsk_cnn_newsspa.py --action=run-baseline
jit_llvm_init(): detected LLVM version lacks critical functionality, shutting down LLVM backend..
Number of GPUs available : 1
Only GPU number 0 used.
```

I assume that this is then just a harmless warning?

**Comment by merlinND** [comment]
Yes, if the CUDA backend works fine for you, feel free to ignore that warning message.
