### ISSUE TITLE
Compatibility between Tensorflow 2.10-2.12 and Sionna 0.16.2

### ISSUE THREAD

**Issue by GKasperF** [NVlabs/sionna#376]
This is a rather minor issue, but it seems some changes in 0.16.2 made it not entirely compatible with previous TensorFlow versions.
For example, the method sample_positions from the class CoverageMap has the following line:
https://github.com/NVlabs/sionna/blob/7eb04f43356333386b4361361188e3810620a0d8/sionna/rt/coverage_map.py#L463

However, [up to TensorFlow 2.12, divide_no_nan only takes inputs with dtype float32 or float64](https://www.tensorflow.org/versions/r2.10/api_docs/python/tf/math/divide_no_nan). This was [updated in 2.13](https://www.tensorflow.org/versions/r2.13/api_docs/python/tf/math/divide_no_nan).

Please clarify in the documentation the TensorFlow requirements.

**Comment by SebastianCa** [comment]
Hi @GKasperF,

thank you for reporting this issue and its detailed investigation. We will fix the issue with the next release of Sionna.
An obvious workaround is to use TensorFlow 2.13 (and newer).

**Comment by SebastianCa** [comment]
Fixed in Sionna v0.17
