### ISSUE TITLE
confused on perfect CSI simulation result

### ISSUE THREAD

**Issue by vanwayplus** [NVlabs/sionna#379]
Hi, I runed the original jupyter notebook without changing anything. [https://github.com/nvlabs/sionna/blob/main/examples/Sionna_tutorial_part4.ipynb](https://github.com/nvlabs/sionna/blob/main/examples/Sionna_tutorial_part4.ipynb)
And I got this result like this （attached）
So what I am wondering is shouldn't the perfect CSI plot be "perfect"m like a fall in SNR=-3.0? Why in some specific settings like you provided in this file they come in a curve? 
![image](https://github.com/NVlabs/sionna/assets/88694167/1c199a0b-800b-42fe-a091-5cbf3037b17d)

**Comment by jhoydis** [comment]
Hi @vanwayplus,

The BER curve you shared looks identical to the one in the notebook. Could you re-explain what is bothering you?

**Comment by vanwayplus** [comment]
Hi @jhoydis 
Yes, as I understand, the BER of the perfect CSI curve should be always 0 since we already know the accurate status.But in the figure it comes in a curve

**Comment by gc1905** [comment]
Hi @vanwayplus. The CSI used by the receiver is perfect but not estimated - this is true. However, please remember that the input signal is still affected by AWGN with power indicated on x-axis, which leads to BER degradation. There may be also other reasons for BER degradation depending on specific scenario, e.g., the MIMO channel matrix may be nearly singular.

**Comment by SebastianCa** [comment]
This issue appears to be solved.

As pointed out by @gc1905, the perfect CSI curve still includes Gaussian noise (otherwise, no SNR could be defined).
