### ISSUE TITLE
Problem with PanelArray() class show() function

### ISSUE THREAD

**Issue by pedrohenriiique** [NVlabs/sionna#38]
**Problem:**
In the beginner tutorial part 3: advanced link level simulations, when executing the command "UT_ARRAY.show()" the following error occurs: "Type Error: float() argument must be a string or a number, not 'MarkStyle'".

**Possible solution:**
The error happens because in the show() function of the PanelArray() class, marker_vert and marker_horz are objects and the argument 'marker' must be a string. The possible solution is to use the get_marker() function which returns a string. This way:
marker = marker_vert.get_marker()
marker = marker_horz.get_marker()

Best regards,
Pedro

**Comment by jhoydis** [comment]
Ok. I can reproduce the error in Colab. Will be fixed in the next release. Thanks.
