### ISSUE TITLE
About automatic repeat request (ARQ)

### ISSUE THREAD

**Issue by wsxtyrdd** [NVlabs/sionna#40]
**Additional context**
Excellent project! 
Do you plan to support ARQ in future releases?

**Comment by wsxtyrdd** [comment]
One additional question:
Small updates to support normalized minsum algorithm, i.e., msg = sign_val * msg_e * 0.8 in _cn_update_minsum_mapfn function of  class LDPCBPDecoder, which may make the ber performance slightly better.

**Comment by SebastianCa** [comment]
It’s great to hear that you like Sionna.

I’m not exactly sure what you mean by “ARQ support”, but I assume it relates to the incremental redundancy (IR) of LDPC codes. Supporting IR is currently not our highest priority, but could be definitively integrated in a future release.

Regarding your question about minsum decoding:  it is already possible to scale the VN2CN messages with trainable weights.If initialized with a constant value, these weights allow scaled min-sum decoding (see [Weighted BP example](https://nvlabs.github.io/sionna/examples/Weighted_BP_Algorithm.html#Damped-BP)).

Remark: Closing this thread as this is not really an issue. Please consider starting a new discussion in the forum for future feature requests.
