### ISSUE TITLE
Review required for my pull request #430

### ISSUE THREAD

**Issue by manideepabc** [NVlabs/sionna#434]
Hello,

I recently made a pull request(A new feature to add RIS to the simulator), and it has been stuck in the review phase. No one has been assigned to review the code and merge it. Can you tell me the timeline for a pull request to be approved?

**Comment by SebastianCa** [comment]
Hi @manideepabc,

sorry for the long delay and thank you for the PR. We'll start the review of the PR shortly and keep you updated.
I'll close this issue and refer to #430 for further discussions.
