### ISSUE TITLE
Data set used by Neural network

### ISSUE THREAD

**Issue by Taraneh1367** [NVlabs/sionna#44]
Hello,

I was wondering if it is possible to sene me the data set you used for the neural receiver's training?

I wanted to ask you if  you have any other example that model the LS channel estimator using neural receiver? I need a data set to just model LS Channel estimator using neural network.

Any help from you is really appreciated,

**Comment by faycalaa** [comment]
Hi,

I suppose that you are referring to the two notebooks showing how to train a neural receiver ([Part 4: Toward Learned Receivers](https://nvlabs.github.io/sionna/examples/Sionna_tutorial_part4.html) and [Neural Receiver for OFDM SIMO Systems](https://nvlabs.github.io/sionna/examples/Neural_Receiver.html)).

For both notebooks, no dataset is used as (synthetic) samples are generated one-the-fly by randomly sampling bits and transmitting these QAM-OFDM modulated bits over a stochastic 3GPP CDL channel model simulated in the frequency domain. The obtained channel outputs serve as inputs to the neural receiver, and the bits as labels for training. The transmitter and channel are implemented using the corresponding Sionna components, as shown in the notebook. These notebooks are therefore self-sufficient to train and evaluate the neural receiver.

Note that in these notebooks, the aim of the neural receiver is not to model the [LS channel estimator that is implemented in Sionna](https://nvlabs.github.io/sionna/api/ofdm.html?highlight=lschannelestimator#sionna.ofdm.LSChannelEstimator), as the neural receiver replaces the estimator, equalizer, and demapper. The LS estimator, [LMMSE equalizer](https://nvlabs.github.io/sionna/api/ofdm.html?highlight=lmmse#sionna.ofdm.LMMSEEqualizer), and [demapper](https://nvlabs.github.io/sionna/api/mapping.html?highlight=demapper#sionna.mapping.Demapper) are used to implement a receiver that serves as baseline for benchmarking the neural receiver.

Closing as this is not an issue. Please consider starting a new discussion.

**Comment by Taraneh1367** [comment]
Thanks for your explanation. I understood.
