### ISSUE TITLE
Paths with zero amplitude and zero phase. 

### ISSUE THREAD

**Issue by abrxao** [NVlabs/sionna#442]
I’m trying to get the amplitude values using paths.Cir(), but it returns me path with amplitude and phase zero.

paths = scene.compute_paths(max_depth=1)
a, tau = paths.cir()

![Captura de tela de 2024-05-18 13-05-23](https://github.com/NVlabs/sionna/assets/101681023/42e5ae69-5e14-492f-8f2d-d6a82eedee32)

**Comment by abrxao** [comment]
My scene has two transmitters and four receivers. This error is messing me up, cause when i convert the amplitude to dB scale using np.log10(tf.abs(a).numpy()) compiler throw me a warning. "RuntimeWarning: divide by zero encountered in log10:  print( 20*np.log10(tf.abs(ampli_s[i][0,0,1,0].numpy())))"

This only occurs when i have multyple receivers.

**Comment by SebastianCa** [comment]
Hi @abrxao,

The [Path.CIR](https://nvlabs.github.io/sionna/api/rt.html#sionna.rt.Paths.cir) function uses zero-padding (or cropping) to maintain constant tensor dimensions. This zero-padding can result in zero values within your amplitude tensor, which causes the RuntimeWarning: divide by zero encountered in log10 when you attempt to convert these values to the dB scale using np.log10.

To address this, you can add a small offset to the amplitude values before converting them to dB to avoid taking the log of zero.

**Comment by abrxao** [comment]
> Hi @abrxao,
> 
> The [Path.CIR](https://nvlabs.github.io/sionna/api/rt.html#sionna.rt.Paths.cir) function uses zero-padding (or cropping) to maintain constant tensor dimensions. This zero-padding can result in zero values within your amplitude tensor, which causes the RuntimeWarning: divide by zero encountered in log10 when you attempt to convert these values to the dB scale using np.log10.
> 
> To address this, you can add a small offset to the amplitude values before converting them to dB to avoid taking the log of zero.

Thank you!
