### ISSUE TITLE
Coverage map power/amplitude path summation and paths phases - question

### ISSUE THREAD

**Issue by msomeone** [NVlabs/sionna#455]
Hello,
as far as i understand, power computation for each coverage map cell is a sum of two separate coverage maps - first of coverage map of reflections and scattering and second one - of diffraction coverage map. Each path's amplitude is computed in cell hit point and accumulated without considering electric field phase. Which is done on purpose. 

Maybe there are other users or students using this amazing software will be interested if you can share with us the reasoning behind such power summation? 

(from studying sionna electromagnetic primer i'd expect that all 'received' E-fields are summed (including phase dependency present in 'spatial' exp(... * r) / r term), and cells power or loss is then computed from summed E-field amplitude. 

And maybe there is additional reasoning to sum reflection&scattering and diffraction as 'powers' rather than fields.
Thanks in advance for your time if you find this question worth explanation.

Would love to contribute a PR to electromagnetic primer with explanation:) but i dont know the explanation yet...

**Comment by jhoydis** [comment]
Hi @msomeone,

The intuition behind a coverage map is that you want to average out constructive/ destructive interference, i.e., the small-scale fading. For this reason, you add the energy of the paths in a non-coherent manner. We actually never compute for coverage maps the exact field at a precise precision within a cell, but rather integrate the energy density of all rays hitting a cell. You have probably seen [this part](https://nvlabs.github.io/sionna/api/rt.html#coverage-map) of the documentation on coverage maps which explains this.

The reason why diffraction is handled separately from los/reflections/scattering is that the path tracing algorithms are different.

**Comment by msomeone** [comment]
Hi @jhoydis ,
Thank you for explaining. Somehow i've missed documentation about coverage map computation. Is there some reason why integrating over flat cell surface is preferred over any other methods (for example considering each cell as "reception sphere" and integrating over its surface, or maybe a cube)?
Thanks!

**Comment by jhoydis** [comment]
Yes, there is. When a ray hits the cell surface, we compute the "footprint" ds of the ray on the surface typically as rho_1 * rho_2 * 4 * PI / N / cos(theta_i), where 4PI/N is the solid angle corresponding to this ray (assuming that N rays where shot uniformly on a sphere), theta_i is the angle of incidence w.r.t the normal of the cell, and rho_1, rho_2 are the radii of curvature of the ray tube at the intersection point. For spherical waves, we typically have rho_1* rho_2= r^2, where r is the distance travelled by the wave. 

Integrating over a cube is in principle possible, but it poses quite a few algorithmic challenges. Reception spheres do not really make sense here.

**Comment by msomeone** [comment]
Thank you for an explanation, helped a lot!
