### ISSUE TITLE
Jupyter kernel crashes when loading Sionna RT scene on GPU

### ISSUE THREAD

**Issue by TheoriginalMMM** [NVlabs/sionna#456]
Hi,

I installed Sionna by following the docker based installation instructions, I found issue #285 which is similar to the problem I am facing. But the suggested solution (extend the docker file with the symbolic link to  libcuda.so.1)  didn't solve my current problem (impossible to load the scene using GPU, but we can do it on CPU only). The error and the problem I get when loading the scene using .py script is the following:
'''
Critical Dr.Jit compiler error: jit_optix_check(): API error 7299 (OPTIX_ERROR_INTERNAL_COMPILER_ERROR): "Internal compiler error" in /project/ext/drjit-core/src/optix_core.cpp:105.
Aborted (core dumped)
'''
Thanks for your help.

**Comment by SebastianCa** [comment]
Hi @TheoriginalMMM,
This seems to be an issue with the drjit package (and potentially your GPU drivers). In this case, I would recommend referring to the [DrJIT support](https://github.com/mitsuba-renderer/drjit) page.

**Comment by GiovanniGeraci** [comment]
Hi @TheoriginalMMM,
Did you eventually solve this? I face the same problem.
Thanks!
