### ISSUE TITLE
Ambiguity in the online ”introduction to Sionna RT“ document

### ISSUE THREAD

**Issue by UniqueOnlyZM** [NVlabs/sionna#480]
The descriptions of ”scene.synthetic_array“ in these two pictures of "https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Introduction.html" seems to contradict each other.
![2](https://github.com/NVlabs/sionna/assets/73770089/467de569-7020-4e5a-a69f-01bbf9835aa7)
![1](https://github.com/NVlabs/sionna/assets/73770089/f9d8e58c-1825-49d3-89d8-3800ac8644f4)

**Comment by jhoydis** [comment]
Hi @UniqueOnlyZM,

Good catch, that is indeed wrong. Antennas are explicitly modeled when `scene.synthetic_array` is set to `False`.
We'll correct that in the next release.

**Comment by jhoydis** [comment]
Fixed.
