### ISSUE TITLE
 The execution halts during raytracing tutorial

### ISSUE THREAD

**Issue by paolofiore90** [NVlabs/sionna#482]
I'm following the raytracing tutorial in [https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Introduction.html](url), and its execution was always flawless when I ran it on the CPU of my laptop. I recently migrated the code on a server with 2 GPUs, and now the execution stops.
The tensorflow error shown is:
**ValueError: Memory growth cannot differ between GPU devices.**

In this part of the code:

```
    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        try:
            tf.config.experimental.set_memory_growth(gpus[0], True)
        except RuntimeError as e:
            print(e)
```

only a GPU is setup for memory control, so I set up a for loop to manage both of the available GPUs on my server.

```
    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        for gpu in gpus:
            try:
                tf.config.experimental.set_memory_growth(gpu, True)
            except RuntimeError as e:
                print(e)
```
                
     In this case, now the execution crashes on the load_scene() function.
     
     I tried to find the farthest line of code that is executed before crashing, and it is this one:

`     cache[(variant, submodule, key)] = result`

     in class MitsubaModule(types.ModuleType):
     
     with 

```
cache = {('cuda_ad_rgb', None, 'CppADIntegrator'): mitsuba.cuda_ad_rgb.CppADIntegrator,
 ('cuda_ad_rgb', None, 'Properties'): mitsuba.cuda_ad_rgb.Properties,
 ('cuda_ad_rgb',
  None,
  'register_integrator'): <function mitsuba.cuda_ad_rgb.PyCapsule.register_integrator>,
 ('cuda_ad_rgb',
  None,
  'ScalarTransform4f'): mitsuba.cuda_ad_rgb.ScalarTransform4f,
 ('cuda_ad_rgb',
  None,
  'load_file'): <function mitsuba.cuda_ad_rgb.PyCapsule.load_file>}
```
  
  I cannot access data inside 'result'.
  
  The execution ends with:
  
  Process finished with exit code 139 (interrupted by signal 11:SIGSEGV), which is a segmentation violation.
  
  These are the specs of the software I'm using:
  

**Ubuntu 20.04 (cannot change this)
Python 3.8.10
Tensorflow 2.13.1
Sionna 0.17.0
CUDA 11.8**

and hardware:

**NVIDIA A30 Tensor Core GPU**

which I think should be ok compatibility-wise.

**Comment by SebastianCa** [comment]
Hi @paolofiore90,

Could you try masking the visible CUDA devices at the beginning of your notebook by adding the following code snippet?
```
import os
gpu_num = 0 # Use "" to use the CPU
os.environ["CUDA_VISIBLE_DEVICES"] = f"{gpu_num}"
```
I hope this helps.

**Comment by paolofiore90** [comment]
I'm really sorry for having bothered you, the problem was not in Sionna, there was a mismatch in the Nvidia drivers and the kernel wasn't recognised. I did a clean nvidia install (something along the lines of [https://medium.com/@wumeng9028/how-to-uninstall-nvidia-driver-and-install-the-latest-driver-in-ubuntu-96c0b2dc4cc4](url)), and now it works!
