### ISSUE TITLE
Output dimensions of sionna.channel.FlatFadingChannel

### ISSUE THREAD

**Issue by choonoKw** [NVlabs/sionna#483]
When I followed Basic MIMO Simulations codes shown in [the link](https://nvlabs.github.io/sionna/examples/Simple_MIMO_Simulation.html?highlight=lmmse_equalizer), sionna.channel.FlatFadingChannel return the output "y" with the dimensions [batch_size, num_rx_ant] -- code block [15]. This is inconsistent with the corresponding dimensions [batch_size, num_rx_ant, num_tx_ant] shown in [the function description](https://nvlabs.github.io/sionna/api/channel.wireless.html?highlight=flatfadingchannel#sionna.channel.FlatFadingChannel).

**Comment by SebastianCa** [comment]
Hi @choonoKw,

You are right, this is a typo in the API documentation. It will be fixed in the next version of Sionna.
