### ISSUE TITLE
How to save the 'InteractiveDisplay' object as the '.eps' or '.pdf' file?

### ISSUE THREAD

**Issue by yashcao** [NVlabs/sionna#495]
How to save the 'InteractiveDisplay' object as the '.eps' or '.pdf' file? 

Although a function 'render_to_file' is provided, it is limited by only "png\ipg....".

```
fig = scene.preview(paths=paths) # Open preview showing paths
scene.render(camera="preview", paths=paths) # Render scene with paths from preview camera
scene.render_to_file(camera="preview",
                     filename="scene.png",
                     paths=paths) # Render scene with paths to file
```

**Comment by SebastianCa** [comment]
Closing as resolved.

**Comment by merlinND** [comment]
For context, neither the interactive rendering nor the offline (Mitsuba-based) rendering methods produce _vector_ graphics. They both produce images. So saving them to PDF would just mean embedding the created image into a PDF file, which you can do yourself as @jhoydis suggested.
