### ISSUE TITLE
Spatial Consistency

### ISSUE THREAD

**Issue by fg111128** [NVlabs/sionna#510]
Hi,
I am simulating MU-MIMO, downlink, using UMi channel model.
I configured single BS and 2 UTs. 
Setting  both UTs at same location  and same orientation, 
Based on "Spatial Consistency", I am expecting their OFDM channels would be identical.

But, the OFDM channels are different.

Thanks in advance,
Felix

**Comment by jhoydis** [comment]
Hi @fg111128,

Spatial consistency guarantees that the channel's large-scale parameters are correlated across space. However, I do not think that it guarantees that the channel impulse response at a given position is always the same.
If you are looking for such a behavior, you should rely on ray tracing.

**Comment by fg111128** [comment]
thanks a lot  Jakov
