### ISSUE TITLE
Discrepancy in LMMSE Performance Between Time-Domain and Frequency-Domain Channel Implementations

### ISSUE THREAD

**Issue by jiaruixu** [NVlabs/sionna#513]
I am experimenting with the example code 'MIMO OFDM Transmissions over the CDL Channel Model'. My goal is to compare the performance of LMMSE with both perfect CSI and estimated CSI. I noticed that when using the time-domain channel implementation, LMMSE with perfect CSI performs worse than LMMSE with estimated CSI in the high Eb/No regime, which is counterintuitive. However, this issue does not occur when I switch to the frequency-domain channel implementation. Could this discrepancy be due to a problem with my simulation settings, or is there a potential issue with the time-domain channel implementation?

Here is the code for reproducing my observation.
[Colab code](https://drive.google.com/file/d/1m8CU2GXpqbxiVvQ15J6ZRX10ymNGAqfv/view?usp=sharing)

**Comment by jhoydis** [comment]
Hi @jiaruixu,

I would rather say that this could be a problem of the way the perfect CSI for time-domain simulations is computed.
It could be related to this line:
```
 h_freq = cir_to_ofdm_channel(self._frequencies, a_freq, tau, normalize=True)
```
This channel frequency response might be slightly different from the one you would obtain when computing the DFT of the complex-baseband equivalent channel impulse ``h_time``. In other word, using ``h_freq`` as perfect CSI might be slightly wrong. Maybe you could give this a try.

**Comment by jiaruixu** [comment]
Thank you! I changed to use the DFT of the `h_time`. The problem is solved.
