### ISSUE TITLE
Support of various antenna patterns in one scene

### ISSUE THREAD

**Issue by akdd11** [NVlabs/sionna#530]
Dear Sionna team,

to support simulations with heterogeneous radio devices, it would be great if the antenna arrays with the corresponding patterns are not linked to the scene, but instead can be set for each radio device individually. Is this a potential feature for future versions?

**Comment by jhoydis** [comment]
Hi @akdd11,

For efficiency reasons, this is currently not an option. All transmitters must use the same antenna array. The same holds for the receivers.

However, you could probably circumvent this by having all devices use an isotropic antenna pattern and equip them with the largest array size in the scene. You could then manually set coefficients in the channel impulse response to zero and apply device-specific antenna patterns on top.  But this is certainly not an efficient solution.

**Comment by akdd11** [comment]
Hi @jhoydis, thanks a lot for the quick response! It's good to know that the feature is not reasonable from an efficiency point of view, then I will go for a workaround implementation.
