### ISSUE TITLE
Issue in generating  Coverage Maps with Diffraction at a higher carrier frequency (30 GHz) in Sionna_Ray_Tracing_Diffraction example

### ISSUE THREAD

**Issue by Jedrek09** [NVlabs/sionna#568]
Initially, I executed this in the Jupyter Notebook, but I encountered both a SyntaxWarning and a NameError while generating the channel impulse response. Before these errors, I was able to successfully visualize all the figures.

I then ran the same example in Google Colab, where I was able to generate most of the graphs and figures. However, I could not generate figures at a higher carrier frequency due to RAM limitations, which led to memory exhaustion. Could you advise on how I might handle this issue in both the cases?

**Comment by jhoydis** [comment]
Hi @Jedrek09,

It is difficult to help without a concrete code example or warning. The notebooks runs fine for me. In case of memory limitations, you can try to downgrade to sionna v0.17 and see if it works.

**Comment by Jedrek09** [comment]
While running Sionna Ray Tracing Diffraction I encountered an issue while executing 
"n = 400
plt.figure()
plt.stem(tau[n]/1e-9, 10*np.log10(np.abs(a[n])**2))
plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
plt.xlabel("Delay (ns)");
plt.ylabel("$|a|^2$ (dB)");"

I got the error 

"<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\c'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\c'
C:\Users\User\AppData\Local\Temp\ipykernel_13784\2688836715.py:4: SyntaxWarning: invalid escape sequence '\p'
  plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
C:\Users\User\AppData\Local\Temp\ipykernel_13784\2688836715.py:4: SyntaxWarning: invalid escape sequence '\c'
  plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
C:\Users\User\AppData\Local\Temp\ipykernel_13784\2688836715.py:4: SyntaxWarning: invalid escape sequence '\p'
  plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
C:\Users\User\AppData\Local\Temp\ipykernel_13784\2688836715.py:4: SyntaxWarning: invalid escape sequence '\c'
  plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[9], line 3
      1 n = 400
      2 plt.figure()
----> 3 plt.stem(tau[n]/1e-9, 10*np.log10(np.abs(a[n])**2))
      4 plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
      5 plt.xlabel("Delay (ns)");

NameError: name 'tau' is not defined
<Figure size 640x480 with 0 Axes>"

The same example when I ran in google colab I was able to execute all the sections except the last. When I ran 

"scene = load_scene(sionna.rt.scene.simple_street_canyon)
scene.frequency = 30e9
scene.tx_array = PlanarArray(num_rows=1,
                             num_cols=1,
                             vertical_spacing=0.5,
                             horizontal_spacing=0.5,
                             pattern="iso",
                             polarization="V")

scene.rx_array = scene.tx_array
scene.add(Transmitter(name="tx",
                      position=[-33,11,32],
                      orientation=[0,0,0]))

scene.add(my_cam)

cm = scene.coverage_map(cm_cell_size=[1,1], num_samples=10e6)
cm_diff = scene.coverage_map(cm_cell_size=[1,1], num_samples=10e6, diffraction=True)
scene.render(my_cam, coverage_map=cm);
scene.render(my_cam, coverage_map=cm_diff);"

My colab was showing "The session expired due to use of all available RAM"

Can you help me to solve this

**Comment by jhoydis** [comment]
I have just run the notebook in Google Colab using a free T4 GPU and I cannot reproduce the first error.

Concerning the memory error, I would suggest that you try to install Sionna v0.17 by changing the corresponding line in the first cell:
``
os.system("pip install sionna==0.17")
``

Please check if the correct version is installed by running
``
print(sionna.__version__)
``

When RIS were introduced in Sionna v0.18, the memory consumption for coverage maps increased. We might try to bring this down in a future release.

**Comment by Jedrek09** [comment]
I have installed Sionna v0.15. Is there any specific suggestion with that or should I go with Sionna 17

**Comment by Jedrek09** [comment]
I have just run the notebook in Google Colab using a free T4 GPU and I got the following error (Image attached)
![1](https://github.com/user-attachments/assets/263f3781-8166-4fe5-93d2-c19028622522)

**Comment by Jedrek09** [comment]
Hi. Can I get a solve for this

**Comment by faycalaa** [comment]
Hi @Jedrek09,

This issue does not seem to be related to Sionna but to a limitation in Colab usage.

**Comment by Jedrek09** [comment]
While executing the code in jupyter notebook the code 
n = 400
plt.figure()
plt.stem(tau[n]/1e-9, 10*np.log10(np.abs(a[n])**2))
plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
plt.xlabel("Delay (ns)");
plt.ylabel("$|a|^2$ (dB)");

 I got the following error 
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\c'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\c'
C:\Users\User\AppData\Local\Temp\ipykernel_8800\2688836715.py:4: SyntaxWarning: invalid escape sequence '\p'
  plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
C:\Users\User\AppData\Local\Temp\ipykernel_8800\2688836715.py:4: SyntaxWarning: invalid escape sequence '\c'
  plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
C:\Users\User\AppData\Local\Temp\ipykernel_8800\2688836715.py:4: SyntaxWarning: invalid escape sequence '\p'
  plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
C:\Users\User\AppData\Local\Temp\ipykernel_8800\2688836715.py:4: SyntaxWarning: invalid escape sequence '\c'
  plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[9], line 3
      1 n = 400
      2 plt.figure()
----> 3 plt.stem(tau[n]/1e-9, 10*np.log10(np.abs(a[n])**2))
      4 plt.title(f"Angle of receiver $\phi: {int(phi[n]/PI*180)}^\circ$");
      5 plt.xlabel("Delay (ns)");

NameError: name 'tau' is not defined
<Figure size 640x480 with 0 Axes>

How to solve this?

**Comment by merlinND** [comment]
Hello @Jedrek09,

Is the variable `tau` computed correctly in a previous cell in the notebook?
Make sure that the cell is executing correctly. If there's an error / exception in that cell, you will not be able to use the variable `tau`.

You can check that it's well defined by simply printing it: `print(tau)`.

**Comment by Jedrek09** [comment]
Yes. The variable tau is computed correctly in the previous cell in the notebook

**Comment by merlinND** [comment]
Does the following code work, meaning it prints the values and then shows the figure?
It shouldn't be possible to get a `NameError` for `tau` if it's computed correctly in the previous cell.

```py
n = 400
print("tau =", tau)
print("a=", a)

plt.figure()
plt.stem(tau[n]/1e-9, 10*np.log10(np.abs(a[n])**2))
plt.show()
```

**Comment by Jedrek09** [comment]
Thanks. The issue has been solved
