### ISSUE TITLE
The problem of object movement in RT mobility simulation

### ISSUE THREAD

**Issue by MyQooo** [NVlabs/sionna#569]
When I was doing the mobility RT simulation, I couldn't change the position of the objects in the scene, so I couldn't move them. I found that the objects in the scene are classified by different materials. For example, if an object has multiple materials, it is divided into multiple objects, and it cannot move at the same time. How can I solve this problem
<img width="1061" alt="1" src="https://github.com/user-attachments/assets/78ad443c-1f8a-4b12-8a15-15641b3b9800">
![Uploading 2.png…]()

**Comment by MyQooo** [comment]
And I would like to ask, can only parts of an object made of different materials be classified as objects separately? If so, how do I move an object with a different material.

**Comment by jhoydis** [comment]
Hi @MyQooo,

Can you please provide a code snippet that allows us to reproduce the behavior you observe? From the code that you have provided, it is impossible to give you any guidance.

**Comment by MyQooo** [comment]
> Hi @MyQooo,
> 
> Can you please provide a code snippet that allows us to reproduce the behavior you observe? From the code that you have provided, it is impossible to give you any guidance.

Of course, the error clip is as follows
<img width="1078" alt="2" src="https://github.com/user-attachments/assets/3dac9bd9-5531-484f-a46c-2f52c8602e07">

**Comment by jhoydis** [comment]
I meant a code snippet that we can use to reproduce the error, not the error message.

**Comment by MyQooo** [comment]
> I meant a code snippet that we can use to reproduce the error, not the error message.

A snippet of code simply changes the coordinates of an object in the scene：
<img width="1136" alt="3" src="https://github.com/user-attachments/assets/bb988a13-3da5-423e-8283-9f91f5f65fa2">

**Comment by MyQooo** [comment]
> I meant a code snippet that we can use to reproduce the error, not the error message.

And this is my scene file, and what I want to do is make the train move through the tunnel, but I can't change the train coordinates

**Comment by MyQooo** [comment]
> I meant a code snippet that we can use to reproduce the error, not the error message.

[scene.zip](https://github.com/user-attachments/files/16977013/scene.zip)

**Comment by jhoydis** [comment]
We need the full code (ideally a Jupyter notebook) that allows us to reproduce the error.
For example, does the [Mobility tutorial](https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Mobility.html) work for you?

**Comment by MyQooo** [comment]
> We need the full code (ideally a Jupyter notebook) that allows us to reproduce the error. For example, does the [Mobility tutorial](https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Mobility.html) work for you?

I have provided you with the scene file. What I want to do is to make the train run in the tunnel, which requires changing the coordinates of the object of the train. I hope you can have a try, thank you very much

**Comment by MyQooo** [comment]
> We need the full code (ideally a Jupyter notebook) that allows us to reproduce the error. For example, does the [Mobility tutorial](https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Mobility.html) work for you?

**Comment by jhoydis** [comment]
Again, does the mobility tutorial work for you? If yes, then there must be something wrong in the way you setup your scene.

**Comment by MyQooo** [comment]
> Again, does the mobility tutorial work for you? If yes, then there must be something wrong in the way you setup your scene.

I haven't actually tried the mobility tutorial yet, so I'll give it a try.

**Comment by jhoydis** [comment]
Why did you close the issue? Was the problem solved? If yes, how?

**Comment by MyQooo** [comment]
> Why did you close the issue? Was the problem solved? If yes, how?

I tried the tutorial and it had no problems. But my problem still hasn't been solved. In fact, one of the core problems I found was that an object with different materials would be divided into several different obj objects.

**Comment by jhoydis** [comment]
Yes, this behavior is normal. Every object can only have a single material. You would simply need to move the different objects simultaneously.

**Comment by MyQooo** [comment]
Unfortunately, in a scene with only three materials, my attempt to move one still failed.
<img width="467" alt="7" src="https://github.com/user-attachments/assets/9b4919a9-af2c-4b33-8bff-ed50ca7cae67">
<img width="854" alt="8" src="https://github.com/user-attachments/assets/17e78b5b-fd40-4d8d-a513-f8fd8296310d">
<img width="977" alt="9" src="https://github.com/user-attachments/assets/70be874e-5dc5-40d0-a476-3edf2569c5ee">

**Comment by jhoydis** [comment]
Hi, I had a quick look at your xml file. It seems that the object ids do not start with "mesh-". Did you create the scene using the Blender export?

**Comment by merlinND** [comment]
As a quick workaround, you could try changing the IDs of the shapes in your scene's XML file to start with `mesh-`.
We will improve compatibility with different naming conventions in the next Sionna release.
