### ISSUE TITLE
没有场景

### ISSUE THREAD

**Issue by Zhong0501** [NVlabs/sionna#572]
你好，为啥我用移动仿真教程里面的场景，显示没有呢？是作者删除了吗
错误为：
AttributeError: module 'sionna.rt.scene' has no attribute 'simple_street_canyon_with_cars'

**Comment by merlinND** [comment]
Hello @Zhong0501,

Can you please post more details about the code you are trying to run and how you installed Sionna, as well as which version?

The following script should run out-of-the-box after `pip install sionna` (tested with version 0.18.0):

```py
import sionna
from sionna.rt import load_scene

scene = load_scene(sionna.rt.scene.simple_street_canyon_with_cars)
print(scene)
```

If not, you can also try another built-in scene: `load_scene(sionna.rt.scene.etoile)`.

**Comment by Zhong0501** [comment]
Hi， @merlinND ,
Mobility，which in Sionna RT of Tutorials in https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Mobility.html，can't finish Controlling Position and Orientation of Scene Objects.A
![671e1d3968ec657cb7a0129046b4fca](https://github.com/user-attachments/assets/c8ac2dea-35a4-4c1d-9dd0-83ddfc0689a7)
s shown in the picture.
The errors are shown:
  在当前单元格或上一个单元格中执行代码时 Kernel 崩溃。请查看单元格中的代码，以确定故障的可能原因。有关详细信息，请单击 <a href='https://aka.ms/vscodeJupyterKernelCrash'>此处</a>。有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。

**Comment by Zhong0501** [comment]
@merlinND ,Hi,
Mobility，which in Sionna RT of Tutorials in https://nvlabs.github.io/sionna/examples/Sionna_Ray_Tracing_Mobility.html，can't finish Controlling Position and Orientation of Scene Objects.Cannot run the results shown in the picture.
The errors are shown:
        在当前单元格或上一个单元格中执行代码时 Kernel 崩溃。请查看单元格中的代码，以确定故障的可能原因。有关详细信息，请单击 <a href='https://aka.ms/vscodeJupyterKernelCrash'>此处</a>。有关更多详细信息，请查看 Jupyter <a href='command:jupyter.viewOutput'>log</a>。
        
        
![671e1d3968ec657cb7a0129046b4fca](https://github.com/user-attachments/assets/6db99a68-5d3e-4dbc-8774-24b1469264e2)

**Comment by merlinND** [comment]
The current message doesn't give much information.
There will probably be some more logs in the terminal that is running the Jupyterlab server.

**Comment by jhoydis** [comment]
Closed due to inactivity.
