### ISSUE TITLE
 'mesh-elm__2.vertex_positions'

### ISSUE THREAD

**Issue by qiangdadi** [NVlabs/sionna#574]
I just want to change the position of an object, but get the error. What is this error means? How can I fix it?

```py
selected_object = "elm__2" 
print("Position: ", scene.get(selected_object).position)
scene.get(selected_object).position += [0., 0., 0.]
```

```
Position:  [0.  0.  2.4]

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[17], line 4
      2 selected_object = "elm__2" 
      3 print("Position: ", scene.get(selected_object).position.numpy())
----> 4 scene.get(selected_object).position += [0., 0., 0.]

File ~/anaconda3/envs/Indoor-localization/lib/python3.9/site-packages/sionna/rt/scene_object.py:176, in SceneObject.position(self, new_position)
    174 new_position = tf.cast(new_position, rdtype)
    175 # [num_vertices*3]
--> 176 vertices = scene_params[f'mesh-{self.name}.vertex_positions']
    177 # [num_vertices,3]
    178 vertices = mi_to_tf_tensor(vertices, rdtype)

File ~/anaconda3/envs/Indoor-localization/lib/python3.9/site-packages/mitsuba/python/util.py:53, in SceneParameters.__getitem__(self, key)
     52 def __getitem__(self, key: str):
---> 53     value = self.__get_value(key)
     55     if key not in self.update_candidates:
     56         self.update_candidates[key] = _jit_id_hash(value)

File ~/anaconda3/envs/Indoor-localization/lib/python3.9/site-packages/mitsuba/python/util.py:45, in SceneParameters.__get_value(self, key)
     44 def __get_value(self, key: str):
---> 45     value, value_type, node, _ = self.properties[key]
     47     if value_type is not None:
     48         value = self.get_property(value, value_type, node)

KeyError: 'mesh-elm__2.vertex_positions'
```

![Uploading Screenshot from 2024-09-16 15-08-11.png…]()

**Comment by jhoydis** [comment]
Hi @qiangdadi,

I think that this issue is related to your specific scene. Did you create it with Blender and then export it to the Mitsuba scene format? You can check in the xml file that the ids of all shape should start with "mesh=", like in this example:



	<shape type="ply" id="mesh-floor">
		<string name="filename" value="meshes/floor.ply"/>
		<boolean name="face_normals" value="true"/>
		<ref id="mat-itu_metal" name="bsdf"/>
	</shape>

**Comment by qiangdadi** [comment]
> Hi @qiangdadi,
> 
> I think that this issue is related to your specific scene. Did you create it with Blender and then export it to the Mitsuba scene format? You can check in the xml file that the ids of all shape should start with "mesh-", like in this example:
> 
> ```
> 
> 
> 	<shape type="ply" id="mesh-floor">
> 		<string name="filename" value="meshes/floor.ply"/>
> 		<boolean name="face_normals" value="true"/>
> 		<ref id="mat-itu_metal" name="bsdf"/>
> 	</shape>
> ```

![Screenshot from 2024-09-16 15-41-57](https://github.com/user-attachments/assets/dbbae06d-21da-4a92-b016-41c035f0a226)
Should I change all the ids and make them start with 'mesh-'?

**Comment by jhoydis** [comment]
You could try, but I would suggest that you create your scene with the Blender to Mitsuba export plugin.

**Comment by qiangdadi** [comment]
> You could try, but I would suggest that you create your scene with the Blender to Mitsuba export plugin.

I tried to import  my own scene in Blender and export it with Blender to Mitsuba export plugin. But it didn't take any effect. The shape ids keep the same as before. Should I recreate the scene in Blender?

**Comment by jhoydis** [comment]
I do not think that you need to recreate the scene. Which version of Blender and the Mitsuba-Blender plugin are you using?

**Comment by qiangdadi** [comment]
> I do not think that you need to recreate the scene. Which version of Blender and the Mitsuba-Blender plugin are you using?
Blender 3.3.21, Mitsuba V3.5.0

**Comment by qiangdadi** [comment]
> I do not think that you need to recreate the scene. Which version of Blender and the Mitsuba-Blender plugin are you using?

Blender 3.3.21, Mitsuba V3.5.0

**Comment by qiangdadi** [comment]
Chang the id fix my problem. And thanks for your answer!!!
