### ISSUE TITLE
Sionna RT backpropagation

### ISSUE THREAD

**Issue by qiangdadi** [NVlabs/sionna#575]
The gradient is zero during backpropagation.

**Comment by jhoydis** [comment]
Hi @qiangdadi,

You need to provide more context to report an issue.

**Comment by qiangdadi** [comment]
I want to optimize the placement of an object. But when I try this , I failed to get the gradient of the object's position.
Then I find this is because the object's position is not trainable.
I want to make a scene object's position trainable. How can I achieve this? And why I fail?

**Comment by qiangdadi** [comment]
I want to optimize the placement of an object. But when I try this , I failed to get the gradient of the object's position.
Then I find this is because the object's position is not trainable.
I want to make a scene object's position trainable. How can I achieve this? And why I fail? 
![Screenshot from 2024-09-16 17-40-53](https://github.com/user-attachments/assets/70c3e448-cdec-4ba4-a2df-35ff3958439f)

**Comment by qiangdadi** [comment]
> Hi @qiangdadi,
> 
> You need to provide more context to report an issue.

Sorry for the trouble made by me. And I tried to provide more details.
