### ISSUE TITLE
The gradient is None during backpropagation

### ISSUE THREAD

**Issue by qiangdadi** [NVlabs/sionna#576]
The gradient is None during backpropagation.
I create the scene and make a environment object position be trainable. And then I calculate the path and cir during forwardpropagation. But I get None grad during backpropagation. I want to know if the object position is differentiable?

**Comment by merlinND** [comment]
Hello @qiangdadi,

Please refrain from posting duplicate issues as it increases the workload for maintainers.

As indicated in #575, you will need to provide more details so that we can help. Please post back in #575, including a minimal reproducing example script, and we will reopen the issue.
