### ISSUE TITLE
Issue in GPU Configuration and Imports

### ISSUE THREAD

**Issue by Jedrek09** [NVlabs/sionna#577]
While executing the code 

```py
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib import cm

from sionna import PI
from sionna.rt import load_scene, Transmitter, Receiver, RIS, PlanarArray, \
                      r_hat, normalize, Camera
```       
               
I faced the following error

```
ImportError                               Traceback (most recent call last)
Cell In[8], line 7
      4 from matplotlib import cm
      6 from sionna import PI
----> 7 from sionna.rt import load_scene, Transmitter, Receiver, RIS, PlanarArray, \
      8                       r_hat, normalize, Camera

ImportError: cannot import name 'RIS' from 'sionna.rt' (C:\Users\User\miniconda3\envs\myenv\Lib\site-packages\sionna\rt\__init__.py)
```

How to solve this?

**Comment by merlinND** [comment]
Hello @Jedrek09,

Which version have you installed, and how did you install it?
RIS support is a recent feature that was only added in version 0.18.0.

**Comment by Jedrek09** [comment]
After creative an env and running the command I get the error 

Collecting sionna==0.18
  Using cached sionna-0.18.0-py3-none-any.whl.metadata (5.7 kB)
INFO: pip is looking at multiple versions of sionna to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement tensorflow<2.16.0,>=2.13.0 (from sionna) (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0)
ERROR: No matching distribution found for tensorflow<2.16.0,>=2.13.0





How to solve this

**Comment by Jedrek09** [comment]
2.17.0 is the tensor flow version I have installed

**Comment by jhoydis** [comment]
TF2.17 is not supported by Sionna. You need to downgrade to another version.
Try:
``
pip install tensorflow==2.15
``

**Comment by Jedrek09** [comment]
I get the following error while running pip install tensorflow==2.15 in myenv

ERROR: Could not find a version that satisfies the requirement tensorflow==2.15 (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0)
ERROR: No matching distribution found for tensorflow==2.15

**Comment by jhoydis** [comment]
Which Python version do you have installed?
Maybe you need to downgrade Python as well.

**Comment by Jedrek09** [comment]
The python version I am using is Python 3.12.4

**Comment by Jedrek09** [comment]
Which python version do I need to get

**Comment by jhoydis** [comment]
Please read and follow the installation instructions:
https://nvlabs.github.io/sionna/installation.html
