### ISSUE TITLE
How to make a scene position trainable?

### ISSUE THREAD

**Issue by qiangdadi** [NVlabs/sionna#579]
![Screenshot from 2024-09-16 17-40-53](https://github.com/user-attachments/assets/68c1012a-0a5b-4963-a3a4-39e41e315ab5)
I want to make a scene object's position trainable. How can I achieve this? And why I fail?

**Comment by merlinND** [comment]
Hello @qiangdadi,

This is the third issue that you open about the same problem. Please refrain from opening multiple issues about the same problem as it wastes a lot of the maintainer's time.

As mentioned in #575, you need to provide more information than simply "it doesn't work".
Please post the requested information, including a full minimal reproducing example (self-contained Python script) in issue #575. It will be reopened once you provide the required information.
