### ISSUE TITLE
 Can different speeds be set for multiple RXs (2 RXs) respectively?

### ISSUE THREAD

**Issue by JJwifisensing** [NVlabs/sionna#587]
![Snipaste_2024-09-20_16-52-10](https://github.com/user-attachments/assets/ba17e1de-4585-4e06-b26d-0f7064b2da59)
 In my scenario, there is one TX and two RXs. I want to set the speed for one of the RXs. How can I do this? The API documentation does not seem to mention this.

**Comment by jhoydis** [comment]
Hi @JJwifisensing,

The tensor `rx_velocities` allows you to set for each RX a different velocity vector. Not clear what your issue is.

**Comment by JJwifisensing** [comment]
> 你好@JJwifisensing，
> 
> 张量`rx_velocities`允许您为每个 RX 设置不同的速度矢量。不清楚您的问题是什么。 顺便说一句，这里有个拼写错误，`num_tx`应该是`num_rx`。这个问题将在下一版本中修复。

oh,sorry,I overlooked it.And,Does "num_rx" refer to the sequence in which "rx" is added to the scene? For example, in this code snippet, "rx" is 1 and "rx_C" is 2.
![Uploading Snipaste_2024-09-21_17-29-32.png…]()

**Comment by JJwifisensing** [comment]
> Hi @JJwifisensing,
> 
> The tensor `rx_velocities` allows you to set for each RX a different velocity vector. Not clear what your issue is. BTW, there is typo, `num_tx` should be `num_rx`. This is fixed in the next release.

oh,sorry,I overlooked it.And,Does "num_rx" refer to the sequence in which "rx" is added to the scene? For example, in this code snippet, "rx" is 1 and "rx_C" is 2.
![Snipaste_2024-09-21_17-29-32](https://github.com/user-attachments/assets/b1158ded-c7db-45f2-ace3-0e3be46970bd)

**Comment by jhoydis** [comment]
Yes.
