### ISSUE TITLE
The kernel appears to have died error with Apple M1

### ISSUE THREAD

**Issue by tienviitta** [NVlabs/sionna#59]
I'm having "The kernel appears to have died" error from https://nvlabs.github.io/sionna/examples/Discover_Sionna.ipynb using Apple Mini M1 with macOS 12.6. I have installed Tensorflow as in https://developer.apple.com/metal/tensorflow-plugin/ using https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh.

**Comment by faycalaa** [comment]
As Sionna is based on TensorFlow it does not support all Apple devices. The main issue seems to originate from tf-metal which is needed to access the GPU. A work-around would be to just rely on the CPU in this case.
