### ISSUE TITLE
OFDMDemodulator() issue for a cyclic_prefix equal to zero

### ISSUE THREAD

**Issue by kassankar** [NVlabs/sionna#6]
**Describe the bug**
Using `OFDMDemodulator()` with a `cyclic_prefix =0`  return a resource grid with num_ofdm_symbols dimension equal to zero.

**To Reproduce**
Please find a jupyter notebook as PDF ("OFDMDemod_bug") to reproduce the error.
[OFDMDemod_bug.PDF](https://github.com/NVlabs/sionna/files/8418711/OFDMDemod_bug.PDF)

**Expected behavior**
Based on the `OFDMDemodulator()` description, even with a `cyclic_prefix = 0`, the function should return an output dimension "out: [batch_size, num_tx, num_streams_per_tx, num_ofdm_symbols, fft_size]". However, the function return an output with num_ofdm_symbols = 0.

**Screenshots**
![OFDMDemod_bug](https://user-images.githubusercontent.com/54535624/161769143-877fe842-43b4-4afe-891a-1e6174fa1d14.jpg)

**Additional context**
The bug is directly linked to the `rest` variable in  `OFDMDemodulator()` class, since using "`tf.math.floormod(inputs.shape[-1],
                                self.fft_size + self.cyclic_prefix_length)`" with `cyclic_prefix_length = 0` will return a zero.
As a result, `inputs = inputs[...,:-rest]` will return an output with last dimension equal to zero since `inputs[...,:0]` --> out: (64,1,1,0) (in my example), however the out should be equal to --> out: (64,1,1,1008).

Proposal: provides an `if self.cyclic_prefix_length !=0:` statement before the `rest =....`, and the `inputs = inputs[...,:-rest]` code lines.

**Comment by jhoydis** [comment]
Thanks for raising this issue. We could reproduce it. It will be fixed soon. 
BTW, the issue even exists for arbitrary cyclic_prefix_length, not just for zero.

**Comment by gmarcusm** [comment]
fixed in release v0.8.1. Thanks!
