### ISSUE TITLE
Error installing with tensorflow2.1

### ISSUE THREAD

**Issue by mlscsdn** [NVlabs/sionna#60]
**Describe the bug**
The following error occurred when installing in my tensorflow2.1(with ptthon3.7) environment:
```
File "C:\Downloads\sionna\sionna-main\sionna\utils\misc.py", line 10, in <module>
    from tensorflow.experimental.numpy import log10 as _log10
ModuleNotFoundError: No module named 'tensorflow.experimental'
```

**To Reproduce**
1. Download the compressed file and decompress it;
2. Enter the decompression directory;
3. Switch to your own tensorflow environment（such as：activate TF2.1）
4. pip install sionna

**Screenshots**

**System:**
 - OS: [Windows 10]
 - CUDA version: [10.0]
 - Python version: [3.7.13]
 - TensorFlow version: [2.1.0]

**Comment by jhoydis** [comment]
Sionna requires TensorFlow 2.6 or higher. Could you try upgrading?
