### ISSUE TITLE
ValueError: Cannot convert a partially known TensorShape to a Tensor: (None, 4) at sim_ber() function under MIMO_OFDM_Transmissions_over_CDL project

### ISSUE THREAD

**Issue by saswata-dragneel** [NVlabs/sionna#66]
I'm using the CPU itself for testing. Tensorflow version used - 2.6.2

**_Error faced_**   ---->   ValueError: Cannot convert a partially known TensorShape to a Tensor: (None, 4)
___________________________________________________________________________________________________________________________________________
While running the **Compare Uplink Performance Over the CDL Models** block of the MIMO_OFDM_Transmissions_over_CDL project, I face the TensorShape error under **sim_ber()** function. [Only change I made is replacing num_target_block_errors with num_target_bit_errors. **Rest entire code is same**]

![image](https://user-images.githubusercontent.com/68372243/202103732-df30f644-e20b-4702-9d22-dea5af258971.png)

___________________________________________________________________________________________________________________________________________

Further debugging into the **sim_ber()** function, the exact line where this issue occurs is here (_highlighted_ section) ->

![image](https://user-images.githubusercontent.com/68372243/202105110-3da0e587-8556-4d38-9d2d-aaf4b0573250.png)

___________________________________________________________________________________________________________________________________________

Please refer to the **error logs** as per this .txt file -> 
[TensorShape_issue.txt](https://github.com/NVlabs/sionna/files/10018793/TensorShape_issue.txt)

**Comment by SebastianCa** [comment]
Hi,

We cannot reproduce your issue in our setup.  Could you please try to upgrade TensorFlow to a newer version?

**Comment by saswata-dragneel** [comment]
The versions of **tensorflow** was **2.6.2** & **sionna** was **0.9.0** in which the above issue occured.

However it is resolved with **tensorflow version 2.9.2** & **sionna version 0.11.0**
