### ISSUE TITLE
Assertion Error while using LDPC decoder for code rate  = 0.5 and 64-QAM

### ISSUE THREAD

**Issue by yampati1** [NVlabs/sionna#67]
I am trying to plot BLER vs SNR with respect to MCS table given by 3GPP. I could plot till 16 QAM with all code rates. But when it comes to 64 QAM(no_of_bit_sym = 6), the code shows an error shown in the following image:

![image](https://user-images.githubusercontent.com/51235418/202211130-e1590c1a-576b-41c1-b7d2-b778ce2fd4aa.png)

Any suggestions?

**Comment by SebastianCa** [comment]
Hi,

without having access to the code snippet that produces the error it is difficult to identify your exact problem.
However, it seems as if the shape of the input LLRs of the decoder is not correct. 

Please ensure that the codeword length `n` is a multiple of `num_bits_per_symbol` by either adjusting `n` or by adding "filler" bits (i.e., dummy bits) to the codeword before calling the mapper and remove these positions after the demapping.

**Comment by yampati1** [comment]
Hi,

Thanks for the response and suggestion. By ensuring codeword length in mutiples of no_of_bits, it solved the issue. Thanks
