### ISSUE TITLE
Transmitters with different antenna array models

### ISSUE THREAD

**Issue by paolofiore90** [NVlabs/sionna#673]
Is it possible to setup a scene with multiple transmitters that use different instances of PlanarArray or I am bounded by one type of PlanarArray per simulation?

For example, if I have arrays with the same number of antennas, same spacing, etc... same everything but a different radiation pattern (between arrays, I don't mean I want antennas on the same array to have different patterns), can I do it or do I need to run one simulation for each subset of transmitters that use a specificly defined PlanarArray?

**Comment by faycalaa** [comment]
Hi @paolofiore90,

Sionna supports only the use of a single antenna array shared by all transmitters. You will therefore need to run simulations for each set of transmitters that share the same array configuration.
