### ISSUE TITLE
Significant Performance Discrepancy Between UMI and CDL Channels

### ISSUE THREAD

**Issue by xiaobaijh** [NVlabs/sionna#674]
Dear Sionna Team,

I am currently using the Sionna library for my communication link simulations and have encountered a concerning issue. When applying the same baseline method, I observe a significant performance difference between the UMI and CDL channels. Specifically, in the UMI channel, the Block Error Rate (BLER) does not decrease as the SNR increases, which is unexpected.
![81d7236391edf9e2958da422f848d11](https://github.com/user-attachments/assets/6e727ffc-b9e9-4fb3-9b10-5f61d30357bd)
![401c9728a65ce923a0a3dafcec6b541](https://github.com/user-attachments/assets/b8779e53-0047-427d-8430-2d5af0a2ef08)

I am using the LLMSE channel estimation method in the baseline implementation, alongside the MMSE detection method.

I am unsure what might be causing this discrepancy and would appreciate any insights or suggestions on how to improve the performance in the UMI channel. Are there specific parameters or configurations that I should consider adjusting?

Thank you for your assistance!

**Comment by jhoydis** [comment]
Hi @xiaobaijh,

It is probably related to the pilot pattern which is not sufficiently dense. The UMi channel is more frequency selective and you might need pilots that are less widely spaced in the frequency domain.
