### ISSUE TITLE
Sionna/Mitsuba function incompatibility

### ISSUE THREAD

**Issue by KiteControl** [NVlabs/sionna#683]
I installed the newest version of sionna=0.15.1 and mitsuba=3.6.0 and am getting the following incompatibility error concerning the rotation function. Also mitsuba=3.0.0 is no longer installable, the version has been removed. Is there a workaround for this?

---------------------------------------------------------------------------

```
TypeError                                 Traceback (most recent call last)
Cell In[8], [line 1](vscode-notebook-cell:?execution_count=8&line=1)
----> [1](vscode-notebook-cell:?execution_count=8&line=1) import sionna

File ~/miniconda3/lib/python3.12/site-packages/sionna/__init__.py:19
     [17](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/__init__.py:17) from . import channel
     [18](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/__init__.py:18) from . import signal
---> [19](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/__init__.py:19) from . import rt
     [20](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/__init__.py:20) from .config import *
     [22](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/__init__.py:22) # Instantiate global configuration object

File ~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:30
     [24](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:24)     mi.set_variant('llvm_ad_rgb')
     [26](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:26) ############################################
     [27](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:27) # Objects available to the user
     [28](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:28) ############################################
     [29](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:29) # pylint: disable=wrong-import-position
---> [30](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:30) from .scene import load_scene, Scene
     [31](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:31) from .camera import Camera
     [32](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:32) from .antenna import Antenna, compute_gain, visualize, iso_pattern,\
     [33](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:33)                      dipole_pattern, hw_dipole_pattern, tr38901_pattern,\
     [34](https://file+.vscode-resource.vscode-cdn.net/home/kitecontrol/code/sionna/~/miniconda3/lib/python3.12/site-packages/sionna/rt/__init__.py:34)                      polarization_model_1, polarization_model_2

File ~/miniconda3/lib/python3.12/site-packages/sionna/rt/scene.py:20
...

TypeError: rotate(): incompatible function arguments. The following argument types are supported:
    1. rotate(self, axis: mitsuba.ScalarPoint3f, angle: float) -> mitsuba.ScalarTransform4f
```

**Comment by Nay-Klaimi** [comment]
I have the same problem...
The error occurs immediately after importing Sionna, following its installation... I attempted to modify the code to address this, converting the list to a ScalarPoint3f instance, but the error persisted.
**Python Version:** 3.11.9
**Sionna Version:** 0.16.1 (also tried with 0.19.0)
**mitsuba version:** 3.6.0
**Operating System:** win 11

**Error Traceback:**
```---------------------------------------------------------------------------  
TypeError                                 Traceback (most recent call last)  
Cell In[1], line 1  
----> 1 import sionna  
      2 print(sionna.__version__)  

File d:\...\Lib\site-packages\sionna\__init__.py:19  
     17 from . import channel  
     18 from . import signal  
---> 19 from . import rt  
     20 from .config import *  
     22 # Instantiate global configuration object  

File d:\...\Lib\site-packages\sionna\rt\__init__.py:30  
     24 mi.set_variant('llvm_ad_rgb')  
     26 ############################################  
     27 # Objects available to the user  
     28 ############################################  
     29 # pylint: disable=wrong-import-position  
---> 30 from .scene import load_scene, Scene  
     31 from .camera import Camera  
     32 from .antenna import Antenna, compute_gain, visualize, iso_pattern, dipole_pattern, hw_dipole_pattern, tr38901_pattern, polarization_model_1, polarization_model_2  

File d:\...\Lib\site-packages\sionna\rt\scene.py:20  
     17 import tensorflow as tf  
     19 from .antenna_array import AntennaArray  
---> 20 from .camera import Camera  
     21 from sionna.constants import SPEED_OF_LIGHT  
     22 from .itu_materials import instantiate_itu_materials  

File d:\...\Lib\site-packages\sionna\rt\camera.py:15  
     11 import mitsuba as mi  
     12 import numpy as np  
---> 15 class Camera(OrientedObject):  
     16     # pylint: disable=line-too-long  
     17     r"""Camera(name, position, orientation=[0.,0.,0.], look_at=None)  
     18   
     19     A camera defines a position and view direction for rendering the scene.  
   (...)  
     44         If set to `None`, then ``orientation`` is used to orientate the camera.  
     45     """  
     47     # The convention of Mitsuba for camera is Y as up and look toward Z+.  
     48     # However, Sionna uses Z as up and looks toward X+, for consistency  
     49     # with radio devices.  
     50     # The following transform performs a rotation to ensure Sionna's  
     51     # convention.  
     52     # Note: Mitsuba uses degrees  

File d:\...\Lib\site-packages\sionna\rt\camera.py:53, in Camera()  
     17 r"""Camera(name, position, orientation=[0.,0.,0.], look_at=None)  
     18   
     19 A camera defines a position and view direction for rendering the scene.  
   (...)  
     44         If set to `None`, then ``orientation`` is used to orientate the camera.  
     45     """  
     47 # The convention of Mitsuba for camera is Y as up and look toward Z+.  
     48 # However, Sionna uses Z as up and looks toward X+, for consistency  
     49 # with radio devices.  
     50 # The following transform performs a rotation to ensure Sionna's  
     51 # convention.  
     52 # Note: Mitsuba uses degrees  
---> 53 mi_2_sionna = ( mi.ScalarTransform4f.rotate([0,0,1], 90.0)  
     54             @ mi.ScalarTransform4f.rotate([1,0,0], 90.0) )  
     56 def __init__(self, name, position, orientation=(0.,0.,0.), look_at=None):  
     57  
     58     # Keep track of the "to world" transform.  
     59     # Initialized to identity.  
     60     self._to_world = mi.ScalarTransform4f()  

TypeError: rotate(): incompatible function arguments. The following argument types are supported:  
    1. rotate(self, axis: mitsuba.ScalarPoint3f, angle: float) -> mitsuba.ScalarTransform4f  

Invoked with types: list, float

**Comment by SebastianCa** [comment]
Hi @KiteControl,
can you please manually downgrade to mitsuba 3.5?

**Comment by bchateli** [comment]
Hi !

I experience the same error message when trying to import Sionna:

- I tested with multiple Sionna versions (0.16.1 and 0.19)
- I tested on several systems (Colab and Windows)

Importing Sionna (0.16.1) works on a virtualenv created a few month ago, but not on a new virtualenv (with the same packages). I suspect a change in one of Sionna's dependencies.

Do you have any idea on what is causing this?

Thanks in advance!

**Comment by KiteControl** [comment]
> Hi @KiteControl, can you please manually downgrade to mitsuba 3.5?

Hi, this solution worked. Thanks a lot for the quick response :)

**Comment by merlinND** [comment]
> Do you have any idea on what is causing this?

@bchateli There was a new Mitsuba version released, with which Sionna is not compatible yet. The dependencies of Sionna were not specified "strictly" enough, so any new Sionna install would pull the newest (incompatible) Mitsuba 3.6+ version.
We will push a new version of Sionna shortly that will include more precise versions in its dependencies.

**Comment by SebastianCa** [comment]
This issue should be fixed with the Sionna v.0.19.1 release.

**Comment by sssxxxfan** [comment]
> > Hi [@KiteControl](https://github.com/KiteControl), can you please manually downgrade to mitsuba 3.5?
> 
> Hi, this solution worked. Thanks a lot for the quick response :)

why i still can not solute it,i try mitsuba==3.5,sionna==0.15.1

**Comment by merlinND** [comment]
Hello @sssxxxfan,

If you run:

```bash
pip install --upgrade sionna
pip install mitsuba==3.5.2
```

and try again, what error message do you get?
Please make sure that the Sionna and Mitsuba packages being imported are really these versions, and not another installation from somewhere else on your computer.

**Comment by sssxxxfan** [comment]
Hello@merlinND,
Traceback (most recent call last):
  File "D:\Sionna2\Simulation.py", line 16, in <module>
    from sionna.rt import *
  File "D:\py\envs\myenv\Lib\site-packages\sionna\__init__.py", line 19, in <module>
    from . import rt
  File "D:\py\envs\myenv\Lib\site-packages\sionna\rt\__init__.py", line 30, in <module>
    from .scene import load_scene, Scene
  File "D:\py\envs\myenv\Lib\site-packages\sionna\rt\scene.py", line 20, in <module>
    from .camera import Camera
  File "D:\py\envs\myenv\Lib\site-packages\sionna\rt\camera.py", line 15, in <module>
    class Camera(OrientedObject):
  File "D:\py\envs\myenv\Lib\site-packages\sionna\rt\camera.py", line 60, in Camera
    mi_2_sionna = (mi.ScalarTransform4f.rotate(axis1, 90.0) @
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: rotate(): incompatible function arguments. The following argument types are supported:
    1. rotate(self, axis: mitsuba.ScalarPoint3f, angle: float) -> mitsuba.ScalarTransform4f

Invoked with types: mitsuba.ScalarPoint3f, float

**Comment by sssxxxfan** [comment]
Hi,@merlinND,
my windows=10,sionna ==0.15.1,could not upgrade,mitsuba==3.5.2,still can not work

**Comment by merlinND** [comment]
Hello @sssxxxfan,

This still looks like an error you would get if your Mitsuba version is too high.
In the same script where you encounter this error, could you please add:

```py
import mitsuba as mi
# Optional, enable this if you encounter an error about "you must specify the desired variants":
# mi.set_variant(mi.variants()[0])
print("Mitsuba version:", mi.__version__)
```

If the Mitsuba version is 5.6.0 or higher, it means that you have not installed `mitsuba==3.5.2`, or that you have another installation of `mitsuba` in your environment that is being picked up.

**Comment by sssxxxfan** [comment]
Hi@merlinND,
my windows=10,sionna ==0.15.1,could not upgrade,mitsuba==3.5.2,still can not work.I try pip install sionna=0.16.1 or 0.19.1,the erro is
ERROR: Invalid requirement: 'sionna=0.19.1': Expected end or semicolon (after name and no valid version specifier)

**Comment by merlinND** [comment]
Given the error message, it looks like you mistyped the command to upgrade the module. The correct command is:

```bash
pip install sionna==0.19.1
```

**Comment by sssxxxfan** [comment]
@merlinND ,
sorry,i try it again,it still have erros
ERROR: Could not find a version that satisfies the requirement tensorflow<2.16.0,>=2.13.0 (from sionna) (from versions:
