### ISSUE TITLE
path interaction point

### ISSUE THREAD

**Issue by Zhong0501** [NVlabs/sionna#684]
Hi, the vertices inside the variable paths are the spatial coordinates of the ray interaction points, I draw the scene and vertices on a picture, and connect the lines according to the order in the vertices, but it turns out that some of the interaction points are not in the scope of the scene in reality, what's the reason for this?
![d188bad12c6df4c6e170ba6599de041](https://github.com/user-attachments/assets/08671c42-c65f-4919-9578-24845f2772b3)

**Comment by merlinND** [comment]
Hello @Zhong0501,

By any chance, is there a gap (even very small) in the geometry that the rays could pass through?

As usual, we cannot really help unless we have the full scene (XML + scene files) and code that you used in order to troubleshoot.

**Comment by Zhong0501** [comment]
Thanks, I've solved the problem, the problem is that max_depths means the number of times the ray interacts with the object, I just need to determine the information about the ray's interaction with the object based on the objects in the variable to solve the problem @merlinND
