### ISSUE TITLE
Example 1 broken

### ISSUE THREAD

**Issue by rikluost** [NVlabs/sionna#692]
Example 1 seems to have accidentally deleted rows and does not run any longer.

**Comment by SebastianCa** [comment]
Hi @rikluost,
which exact notebook does not work? I can successfully run [Tutorial Part 1](https://nvlabs.github.io/sionna/examples/Sionna_tutorial_part1.html) in Colab, that seems to work fine.

**Comment by rikluost** [comment]
Hi,

updated my sionna installation to the latest one and did CUDA update too - ended up with a mess. Problem in my end, apologies.

Kind regards
Riku
