### ISSUE TITLE
fec: ldpc: _llr_max attribute overwritten in base LDPCBPDecoder class 

### ISSUE THREAD

**Issue by rediet-orange** [NVlabs/sionna#75]
**Describe the bug**
`_llr_max ` attribute is set in both `LDPC5GDecoder` and `LDPCBPDecoder`. Since the initialization of the latter is done after the setting in the child class, this might create some inconsistency.

**To Reproduce**
Static code analysis, so not required IMO.

**Expected behavior**
Set the value only in one place (e.g. in parent class and passing it as argument).

**Screenshots**
N/A

**System:**
N/A

**GPUs:**
N/A

**Additional context**
N/A

**Comment by SebastianCa** [comment]
Thanks for raising this issue. Will be fixed in the next release.

**Comment by gmarcusm** [comment]
fixed in 0.12.1
