### ISSUE TITLE
test_mimo_ofdm_cdl.py is failing

### ISSUE THREAD

**Issue by catkira** [NVlabs/sionna#85]
![image](https://user-images.githubusercontent.com/13425558/209477684-21cc46de-a97b-45fc-b9bc-6c91e47805a6.png)

can anybody reproduce this?

**Comment by faycalaa** [comment]
Could you share the output from running the tests detailing the reason for the failure?

**Comment by catkira** [comment]
I tried running it with GPU in native Linux, it does not fail there.

**Comment by catkira** [comment]
I assume it was a problem with the system I was running it on the first time. I close this issue now.
